#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "TSAlarmClockModel+Npk.h"
#import "TSNpkAlarmClock.h"
#import "TSNpkAppStatus.h"
#import "TSBatteryModel+Npk.h"
#import "TSNpkBattery.h"
#import "TSConnectedPeripheral+Npk.h"
#import "TSConnectionHistory+Npk.h"
#import "TSMessageAbility+NPK.h"
#import "TSNpkBleConnect.h"
#import "TSPeripheral+Npk.h"
#import "TSPeripheralConnectParam+Npk.h"
#import "TSNpkCamera.h"
#import "TSNpkComDataStorage.h"
#import "TSNpkComKit.h"
#import "TSContactModel+Npk.h"
#import "TSNpkContact.h"
#import "TSNpkBaseDataSync.h"
#import "TSBODailyModel+Npk.h"
#import "TSBOValueItem+Npk.h"
#import "TSNpkBODataSync.h"
#import "TSBPDailyModel+Npk.h"
#import "TSBPValueItem+Npk.h"
#import "TSNpkBPDataSync.h"
#import "TSActivityDailyModel+Npk.h"
#import "TSDailyActivityItem+Npk.h"
#import "TSNpkDailyActivityDataSync.h"
#import "TSNpkECGDataSync.h"
#import "TSHRDailyModel+Npk.h"
#import "TSHRValueItem+Npk.h"
#import "TSNpkHRDataSync.h"
#import "TSNpkSleepDataSync.h"
#import "TSSleepDailyModel+Npk.h"
#import "TSSleepDetailItem+Npk.h"
#import "TSNpkSportDataSync.h"
#import "TSSportItemModel+Npk.h"
#import "TSSportModel+Npk.h"
#import "TSSportSummaryModel+Npk.h"
#import "TSNpkStressDataSync.h"
#import "TSStressDailyModel+Npk.h"
#import "TSStressValueItem+Npk.h"
#import "TSNpkTempDataSync.h"
#import "TSDataSyncConfig+Npk.h"
#import "TSNpkDataSync.h"
#import "TSFemaleHealthConfig+NPK.h"
#import "TSNpkFemaleHealth.h"
#import "TSNpkFileTransfer.h"
#import "TSNpkBloodOxygen.h"
#import "TSNpkBloodPressure.h"
#import "TSDailyActivityGoals+Npk.h"
#import "TSDailyActivityReminder+Npk.h"
#import "TSNpkDailyActivity.h"
#import "TSNpkElectrocardio.h"
#import "TSActivityMeasureParam+Npk.h"
#import "TSNpkActiveMeasure.h"
#import "TSAutoMonitorBPConfigs+Npk.h"
#import "TSAutoMonitorConfigs+Npk.h"
#import "TSAutoMonitorHRConfigs+Npk.h"
#import "TSNpkAutoMonitor.h"
#import "TSNpkHealthBase.h"
#import "TSNpkHeartRate.h"
#import "TSNpkSleep.h"
#import "TSNpkSport.h"
#import "TSNpkStress.h"
#import "TSNpkTemperature.h"
#import "TSNpkKitBase.h"
#import "TSNpkKitInit.h"
#import "TSLanguageModel+Npk.h"
#import "TSNpkLanguage.h"
#import "TSMessageModel+Npk.h"
#import "TSNpkMessage.h"
#import "TSDialModel+NPK.h"
#import "TSNpkPeripheralDial.h"
#import "TSNpkPeripheralFind.h"
#import "TSNpkPrayers.h"
#import "TSPrayerConfigs+NPK.h"
#import "TSPrayerTimes+NPK.h"
#import "TSNpkReminders.h"
#import "TSRemindersModel+Npk.h"
#import "TSNpkRemoteControl.h"
#import "TSDoNotDisturbModel+Npk.h"
#import "TSNpkSetting.h"
#import "TSWristWakeUpModel+Npk.h"
#import "TSNpkTime.h"
#import "TSNpkUnit.h"
#import "TSNpkUserInfo.h"
#import "TSNpkWeather.h"
#import "TSWeatherCodeModel+Npk.h"
#import "TSWeatherDayModel+Npk.h"
#import "TSWeatherHourModel+Npk.h"
#import "TSWeatherModel+Npk.h"
#import "TSNpkWorldClock.h"
#import "TSWorldClockModel+NPK.h"

FOUNDATION_EXPORT double TopStepNewPlatformKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepNewPlatformKitVersionString[];

