// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: pb_stream_param.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TSMetaFileInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbStreamParamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PbStreamParamRoot : GPBRootObject
@end

#pragma mark - TSMetaH264Head

typedef GPB_ENUM(TSMetaH264Head_FieldNumber) {
  TSMetaH264Head_FieldNumber_Fps = 1,
  TSMetaH264Head_FieldNumber_W = 2,
  TSMetaH264Head_FieldNumber_H = 3,
  TSMetaH264Head_FieldNumber_DbEn = 4,
  TSMetaH264Head_FieldNumber_Pref = 5,
};

/**
 * *
 * H264 视频流头部信息
 **/
GPB_FINAL @interface TSMetaH264Head : GPBMessage

/** 帧率 (fps) */
@property(nonatomic, readwrite) int32_t fps;

/** 视频宽度 (像素) */
@property(nonatomic, readwrite) int32_t w;

/** 视频高度 (像素) */
@property(nonatomic, readwrite) int32_t h;

/** 是否启用去块效应 (0:禁用, 1:启用) */
@property(nonatomic, readwrite) int32_t dbEn;

/** 是否包含P帧 (0:不包含, 1:包含) */
@property(nonatomic, readwrite) int32_t pref;

@end

#pragma mark - TSMetaH264Data

typedef GPB_ENUM(TSMetaH264Data_FieldNumber) {
  TSMetaH264Data_FieldNumber_Data_p = 1,
};

/**
 * *
 * H264 视频数据帧
 **/
GPB_FINAL @interface TSMetaH264Data : GPBMessage

/** 视频数据，最大960字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - TSMetaOpusHead

typedef GPB_ENUM(TSMetaOpusHead_FieldNumber) {
  TSMetaOpusHead_FieldNumber_Sampling = 1,
  TSMetaOpusHead_FieldNumber_FrameMs = 2,
  TSMetaOpusHead_FieldNumber_Channel = 3,
};

/**
 * *
 * Opus 音频流头部信息
 **/
GPB_FINAL @interface TSMetaOpusHead : GPBMessage

/** 采样率 (Hz) */
@property(nonatomic, readwrite) int32_t sampling;

/** 帧间隔 (毫秒) */
@property(nonatomic, readwrite) int32_t frameMs;

/** 声道数 (0:单声道, 1:双声道) */
@property(nonatomic, readwrite) int32_t channel;

@end

#pragma mark - TSMetaOpusData

typedef GPB_ENUM(TSMetaOpusData_FieldNumber) {
  TSMetaOpusData_FieldNumber_Data_p = 1,
};

/**
 * *
 * Opus 音频数据帧
 **/
GPB_FINAL @interface TSMetaOpusData : GPBMessage

/** 音频数据，最大960字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - TSMetaOpusEnd

typedef GPB_ENUM(TSMetaOpusEnd_FieldNumber) {
  TSMetaOpusEnd_FieldNumber_Result = 1,
};

/**
 * *
 * Opus 音频流结束信息
 **/
GPB_FINAL @interface TSMetaOpusEnd : GPBMessage

/**
 * *
 * 结束原因
 * 0: 正常结束
 * 1: 空间不足
 * 2: 异常退出
 **/
@property(nonatomic, readwrite) int32_t result;

@end

#pragma mark - TSMetaFileHead

typedef GPB_ENUM(TSMetaFileHead_FieldNumber) {
  TSMetaFileHead_FieldNumber_Path = 1,
  TSMetaFileHead_FieldNumber_Crc32 = 2,
  TSMetaFileHead_FieldNumber_Size = 3,
};

/**
 * *
 * 文件传输头部信息
 **/
GPB_FINAL @interface TSMetaFileHead : GPBMessage

/**
 * *
 * 文件路径
 * 真实路径使用"/"开头
 * 虚拟路径文件夹定义如下：
 * - ota: 固件升级文件
 * - dials_push: 表盘推送文件
 * - music: 音乐文件
 * - sport: 运动相关文件
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

/** 整个文件的CRC32校验码 */
@property(nonatomic, readwrite) int64_t crc32;

/** 文件大小 (字节) */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - TSMetaFileHeadResponse

typedef GPB_ENUM(TSMetaFileHeadResponse_FieldNumber) {
  TSMetaFileHeadResponse_FieldNumber_Result = 1,
  TSMetaFileHeadResponse_FieldNumber_OldSize = 2,
  TSMetaFileHeadResponse_FieldNumber_OldCrc32 = 3,
  TSMetaFileHeadResponse_FieldNumber_PackageSize = 4,
  TSMetaFileHeadResponse_FieldNumber_PackageCount = 5,
};

/**
 * *
 * 文件传输头部响应
 **/
GPB_FINAL @interface TSMetaFileHeadResponse : GPBMessage

/**
 * *
 * 响应结果
 * 0: 正常
 * 1: 设备空间不足
 * 2: 设备忙
 **/
@property(nonatomic, readwrite) int32_t result;

/** 历史文件大小，断点续传时可直接从该偏移开始 */
@property(nonatomic, readwrite) int32_t oldSize;

/** 历史文件已接收部分的CRC32校验码 */
@property(nonatomic, readwrite) int64_t oldCrc32;

/** 每包数据大小，即每次FileData.data的size，目前规定最大960字节 */
@property(nonatomic, readwrite) int32_t packageSize;

/** 每接收到几包数据后，设备响应一次 */
@property(nonatomic, readwrite) int32_t packageCount;

@end

#pragma mark - TSMetaFileData

typedef GPB_ENUM(TSMetaFileData_FieldNumber) {
  TSMetaFileData_FieldNumber_Offset = 1,
  TSMetaFileData_FieldNumber_Data_p = 2,
};

/**
 * *
 * 文件数据传输
 **/
GPB_FINAL @interface TSMetaFileData : GPBMessage

/** 当前数据偏移量 */
@property(nonatomic, readwrite) int32_t offset;

/** 文件数据，最大960字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - TSMetaFileDataResponse

typedef GPB_ENUM(TSMetaFileDataResponse_FieldNumber) {
  TSMetaFileDataResponse_FieldNumber_Result = 1,
  TSMetaFileDataResponse_FieldNumber_FileSize = 2,
  TSMetaFileDataResponse_FieldNumber_FileCrc32 = 3,
};

/**
 * *
 * 文件数据传输响应
 * 传输错误、传输结束、达到回复大小时，设备会主动上报
 **/
GPB_FINAL @interface TSMetaFileDataResponse : GPBMessage

/**
 * *
 * 响应结果
 * 0: 正常
 * 1: offset错误，需从上一帧重传
 * 2: 文件不合法(比如OTA文件不适用于此手表)，需中断传输
 * 3: 对端未进入接收文件流程，需中断传输
 **/
@property(nonatomic, readwrite) int32_t result;

/** 当前已接收的文件大小 */
@property(nonatomic, readwrite) int32_t fileSize;

/** 当前已接收部分的CRC32校验码 */
@property(nonatomic, readwrite) int64_t fileCrc32;

@end

#pragma mark - TSMetaFilePath

typedef GPB_ENUM(TSMetaFilePath_FieldNumber) {
  TSMetaFilePath_FieldNumber_Path = 1,
};

/**
 * *
 * 文件路径信息
 *
 * 关于文件路径/名称限制：
 * 1. 文件夹名长度最大32字节(C语言32字节，有效字符31个)
 * 2. 文件名长度最大64字节(C语言64字节，有效字符63个)
 * 3. 路径最多嵌套两层，如music/1.mp3，或者music/1/2.mp3
 * 4. 路径长度最大128字节（两层文件夹+文件名,最大32+32+64）
 **/
GPB_FINAL @interface TSMetaFilePath : GPBMessage

/** 文件路径，最大127字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@end

#pragma mark - TSMetaDirSpace

typedef GPB_ENUM(TSMetaDirSpace_FieldNumber) {
  TSMetaDirSpace_FieldNumber_Total = 1,
  TSMetaDirSpace_FieldNumber_Free = 2,
};

/**
 * *
 * 文件夹空间信息
 **/
GPB_FINAL @interface TSMetaDirSpace : GPBMessage

/** 总空间 (字节)，未知为0 */
@property(nonatomic, readwrite) uint64_t total;

/** 剩余空间 (字节)，未知为0 */
@property(nonatomic, readwrite) uint64_t free;

@end

#pragma mark - TSMetaFileInfo

typedef GPB_ENUM(TSMetaFileInfo_FieldNumber) {
  TSMetaFileInfo_FieldNumber_Path = 1,
  TSMetaFileInfo_FieldNumber_Size = 2,
};

/**
 * *
 * 文件信息
 **/
GPB_FINAL @interface TSMetaFileInfo : GPBMessage

/** 文件路径，最大127字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

/** 文件大小 (字节)，未知为0 */
@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - TSMetaFileList

typedef GPB_ENUM(TSMetaFileList_FieldNumber) {
  TSMetaFileList_FieldNumber_FilesArray = 1,
};

/**
 * *
 * 文件列表
 * 返回某个文件夹下的文件列表
 * 如果有嵌套文件夹，请铺开作为一个不嵌套的列表
 **/
GPB_FINAL @interface TSMetaFileList : GPBMessage

/** 文件信息列表，最大7个文件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaFileInfo*> *filesArray;
/** The number of items in @c filesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@end

#pragma mark - TSMetaFileOperation

typedef GPB_ENUM(TSMetaFileOperation_FieldNumber) {
  TSMetaFileOperation_FieldNumber_Path = 1,
  TSMetaFileOperation_FieldNumber_Op = 2,
};

/**
 * *
 * 文件操作
 **/
GPB_FINAL @interface TSMetaFileOperation : GPBMessage

/** 文件路径，最大127字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

/**
 * *
 * 操作类型
 * 0: 删除某个文件
 * 1: 清空某个文件夹
 * 2: 其他操作，可能会导致文件变更，对端需要刷新文件列表
 **/
@property(nonatomic, readwrite) int32_t op;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
