// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: pb_common_param.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbCommonParamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PbCommonParamRoot : GPBRootObject
@end

#pragma mark - TSCommonIntRequest

typedef GPB_ENUM(TSCommonIntRequest_FieldNumber) {
  TSCommonIntRequest_FieldNumber_Value = 1,
};

/**
 * =============================================================
 * 公共请求 / Common Request
 * =============================================================
 **/
GPB_FINAL @interface TSCommonIntRequest : GPBMessage

/** 整型请求参数 / Integer request parameter */
@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - TSCommonResponse

typedef GPB_ENUM(TSCommonResponse_FieldNumber) {
  TSCommonResponse_FieldNumber_Result = 1,
};

/**
 * =============================================================
 * 公共响应 / Common Response
 * =============================================================
 **/
GPB_FINAL @interface TSCommonResponse : GPBMessage

/** 0：成功；1：失败；其他值为特殊失败码 / 0: success; 1: failure; other values: special error codes */
@property(nonatomic, readwrite) int32_t result;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
