// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: pb_hsd_param.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TSMetaHsdGameRankingTrend;
@class TSMetaHsdGameRecord;
@class TSMetaHsdHabit;
@class TSMetaHsdParentalControlItem;
@class TSMetaHsdParentalControlPeriod;
@class TSMetaHsdTask;
@class TSMetaHsdUsageInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbHsdParamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PbHsdParamRoot : GPBRootObject
@end

#pragma mark - TSMetaHsdIce

typedef GPB_ENUM(TSMetaHsdIce_FieldNumber) {
  TSMetaHsdIce_FieldNumber_LabelsArray = 1,
};

/**
 * =============================================================
 * ICE 标签（0x02-0x59 设置）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdIce : GPBMessage

/** ICE 标签列表，最多 3 条，每条 UTF-8 最大 63 字节 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *labelsArray;
/** The number of items in @c labelsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger labelsArray_Count;

@end

#pragma mark - TSMetaHsdParentalControlPeriod

typedef GPB_ENUM(TSMetaHsdParentalControlPeriod_FieldNumber) {
  TSMetaHsdParentalControlPeriod_FieldNumber_Start = 1,
  TSMetaHsdParentalControlPeriod_FieldNumber_End = 2,
  TSMetaHsdParentalControlPeriod_FieldNumber_Repeat = 3,
};

/**
 * 家长模式时段
 **/
GPB_FINAL @interface TSMetaHsdParentalControlPeriod : GPBMessage

/** 开始时间，零点开始的偏移分钟数；start == end 表示全天 */
@property(nonatomic, readwrite) int32_t start;

/** 结束时间，零点开始的偏移分钟数；start > end 表示跨天 */
@property(nonatomic, readwrite) int32_t end;

/** 星期重复标志位（bit0=周一 … bit6=周日），跨天时为起始日；0 表示仅一次 */
@property(nonatomic, readwrite) int32_t repeat;

@end

#pragma mark - TSMetaHsdParentalControlItem

typedef GPB_ENUM(TSMetaHsdParentalControlItem_FieldNumber) {
  TSMetaHsdParentalControlItem_FieldNumber_Id_p = 1,
  TSMetaHsdParentalControlItem_FieldNumber_IsEnabled = 2,
  TSMetaHsdParentalControlItem_FieldNumber_Mode = 3,
  TSMetaHsdParentalControlItem_FieldNumber_PeriodsArray = 4,
};

/**
 * 家长模式功能项
 **/
GPB_FINAL @interface TSMetaHsdParentalControlItem : GPBMessage

/** 功能动作 ID */
@property(nonatomic, readwrite) int32_t id_p;

/** 本项开关 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 0-时段内禁用，1-时段内允许 */
@property(nonatomic, readwrite) int32_t mode;

/** 时段列表，max_count:10 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdParentalControlPeriod*> *periodsArray;
/** The number of items in @c periodsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger periodsArray_Count;

@end

#pragma mark - TSMetaHsdParentalControl

typedef GPB_ENUM(TSMetaHsdParentalControl_FieldNumber) {
  TSMetaHsdParentalControl_FieldNumber_IsEnabled = 1,
  TSMetaHsdParentalControl_FieldNumber_ItemsArray = 2,
};

/**
 * 家长模式
 **/
GPB_FINAL @interface TSMetaHsdParentalControl : GPBMessage

/** 家长模式总开关 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 功能列表，每包 max_count:7 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdParentalControlItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaHsdClassroomMode

typedef GPB_ENUM(TSMetaHsdClassroomMode_FieldNumber) {
  TSMetaHsdClassroomMode_FieldNumber_IsEnabled = 1,
  TSMetaHsdClassroomMode_FieldNumber_Start = 2,
  TSMetaHsdClassroomMode_FieldNumber_End = 3,
  TSMetaHsdClassroomMode_FieldNumber_Repeat = 4,
};

/**
 * =============================================================
 * 课堂模式（0x02-0x5C 获取 / 0x5D 设置）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdClassroomMode : GPBMessage

/** 是否开启 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 开始时间，零点开始的偏移分钟数 */
@property(nonatomic, readwrite) int32_t start;

/** 结束时间，零点开始的偏移分钟数 */
@property(nonatomic, readwrite) int32_t end;

/** 星期重复标志位（bit0=周一 … bit6=周日） */
@property(nonatomic, readwrite) int32_t repeat;

@end

#pragma mark - TSMetaHsdTask

typedef GPB_ENUM(TSMetaHsdTask_FieldNumber) {
  TSMetaHsdTask_FieldNumber_Id_p = 1,
  TSMetaHsdTask_FieldNumber_Time = 2,
  TSMetaHsdTask_FieldNumber_Label = 3,
  TSMetaHsdTask_FieldNumber_IsEnabled = 4,
  TSMetaHsdTask_FieldNumber_Repeat = 5,
  TSMetaHsdTask_FieldNumber_Type = 6,
  TSMetaHsdTask_FieldNumber_State = 7,
  TSMetaHsdTask_FieldNumber_Coins = 8,
  TSMetaHsdTask_FieldNumber_Description_p = 9,
  TSMetaHsdTask_FieldNumber_IsTimeEnabled = 10,
};

/**
 * =============================================================
 * 任务 & 奖励（0x02-0x5E 获取 / 0x5F 设置 / 0x60 兑换）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdTask : GPBMessage

/** 任务 ID */
@property(nonatomic, readwrite) int32_t id_p;

/** 执行时间，距零点的偏移分钟数，如 11:30 = 11*60+30 */
@property(nonatomic, readwrite) int32_t time;

/** 标签，UTF-8 最大 32 字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

/** 是否启用 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 星期重复标志位，0 表示仅一次 */
@property(nonatomic, readwrite) int32_t repeat;

/** 任务类型（0-22，见 TSHsdTaskType；取值由 FitCloud 推断，待固件确认） */
@property(nonatomic, readwrite) int32_t type;

/** 当天任务状态：0 未开始，1 进行中，2 已完成 */
@property(nonatomic, readwrite) int32_t state;

/** 完成任务后奖励的金币数 */
@property(nonatomic, readwrite) int32_t coins;

/** 详细描述，UTF-8 最大 100 字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/** 是否需要设置时间，false 则设备不显示时间 */
@property(nonatomic, readwrite) BOOL isTimeEnabled;

@end

#pragma mark - TSMetaHsdTaskInfo

typedef GPB_ENUM(TSMetaHsdTaskInfo_FieldNumber) {
  TSMetaHsdTaskInfo_FieldNumber_TotalCoins = 1,
  TSMetaHsdTaskInfo_FieldNumber_ItemsArray = 2,
};

/**
 * 任务信息：列表分包时每一包都是一个完整的 TSMetaHsdTaskInfo；
 * 下发方向每包都携带 totalCoins，读取方向 SDK 只取第 0 包的 totalCoins。
 **/
GPB_FINAL @interface TSMetaHsdTaskInfo : GPBMessage

/** 当前总金币数 */
@property(nonatomic, readwrite) int32_t totalCoins;

/** 任务列表，最多 5 条 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdTask*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaHsdTaskExchangeResult

typedef GPB_ENUM(TSMetaHsdTaskExchangeResult_FieldNumber) {
  TSMetaHsdTaskExchangeResult_FieldNumber_Success = 1,
};

GPB_FINAL @interface TSMetaHsdTaskExchangeResult : GPBMessage

/** 是否兑换成功 */
@property(nonatomic, readwrite) BOOL success;

@end

#pragma mark - TSMetaHsdHabit

typedef GPB_ENUM(TSMetaHsdHabit_FieldNumber) {
  TSMetaHsdHabit_FieldNumber_Id_p = 1,
  TSMetaHsdHabit_FieldNumber_Type = 2,
  TSMetaHsdHabit_FieldNumber_Label = 3,
  TSMetaHsdHabit_FieldNumber_Time = 4,
  TSMetaHsdHabit_FieldNumber_Duration = 5,
  TSMetaHsdHabit_FieldNumber_Repeat = 6,
  TSMetaHsdHabit_FieldNumber_State = 7,
  TSMetaHsdHabit_FieldNumber_ReachGoalDays = 8,
  TSMetaHsdHabit_FieldNumber_MaxReachGoalDays = 9,
  TSMetaHsdHabit_FieldNumber_TaskDays = 10,
  TSMetaHsdHabit_FieldNumber_AssociatedFunction = 11,
  TSMetaHsdHabit_FieldNumber_RemindDuration = 12,
  TSMetaHsdHabit_FieldNumber_RemindAdvance = 13,
  TSMetaHsdHabit_FieldNumber_LatestAchieveGoalMonth = 14,
  TSMetaHsdHabit_FieldNumber_LatestAchieveGoalDay = 15,
  TSMetaHsdHabit_FieldNumber_AchieveGoalRepeat = 16,
};

/**
 * =============================================================
 * 习惯（0x02-0x61 获取 / 0x62 设置）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdHabit : GPBMessage

/** 习惯 ID */
@property(nonatomic, readwrite) int32_t id_p;

/** 习惯类型：0 自定义(label 有效)，1 运动，2 学习，3 睡眠 */
@property(nonatomic, readwrite) int32_t type;

/** 标签，UTF-8 最大 32 字节 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

/** 执行时间，距零点的偏移分钟数 */
@property(nonatomic, readwrite) int32_t time;

/** 习惯时长（分钟） */
@property(nonatomic, readwrite) int32_t duration;

/** 星期重复标志位，0 表示仅一次 */
@property(nonatomic, readwrite) int32_t repeat;

/** 习惯状态：0 初始，1 进行中，2 已完成，3 已过期，4 已关闭，5 已删除 */
@property(nonatomic, readwrite) int32_t state;

/** 已达成目标天数 */
@property(nonatomic, readwrite) int32_t reachGoalDays;

/** 最大达成目标天数 */
@property(nonatomic, readwrite) int32_t maxReachGoalDays;

/** 任务天数 */
@property(nonatomic, readwrite) int32_t taskDays;

/** 关联功能：0 无，1 运动 */
@property(nonatomic, readwrite) int32_t associatedFunction;

/** 提醒时长（秒） */
@property(nonatomic, readwrite) int32_t remindDuration;

/** 提前提醒分钟数 */
@property(nonatomic, readwrite) int32_t remindAdvance;

/** 最近达成目标月份 [1-12] */
@property(nonatomic, readwrite) int32_t latestAchieveGoalMonth;

/** 最近达成目标日期 [1-31] */
@property(nonatomic, readwrite) int32_t latestAchieveGoalDay;

/** 过去一周达成目标的星期标志位 */
@property(nonatomic, readwrite) int32_t achieveGoalRepeat;

@end

#pragma mark - TSMetaHsdHabitList

typedef GPB_ENUM(TSMetaHsdHabitList_FieldNumber) {
  TSMetaHsdHabitList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaHsdHabitList : GPBMessage

/** 习惯列表，最多 10 条 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdHabit*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaHsdUsageInfo

typedef GPB_ENUM(TSMetaHsdUsageInfo_FieldNumber) {
  TSMetaHsdUsageInfo_FieldNumber_Type = 1,
  TSMetaHsdUsageInfo_FieldNumber_Count = 2,
};

/**
 * =============================================================
 * 使用统计（0x02-0x63 应用 / 0x64 游戏 / 0x65 重置）
 * 列表分包：每包一天，分包序号 = 距今天的天数偏移（0 今天，1 昨天 …）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdUsageInfo : GPBMessage

/** 类型：0x63 为应用类型（0-47），0x64 为游戏类型（0-24） */
@property(nonatomic, readwrite) int32_t type;

/** 当天累计次数 */
@property(nonatomic, readwrite) int32_t count;

@end

#pragma mark - TSMetaHsdUsageInfoList

typedef GPB_ENUM(TSMetaHsdUsageInfoList_FieldNumber) {
  TSMetaHsdUsageInfoList_FieldNumber_ItemsArray = 1,
  TSMetaHsdUsageInfoList_FieldNumber_Timestamp = 2,
};

GPB_FINAL @interface TSMetaHsdUsageInfoList : GPBMessage

/** 使用信息列表（一天），最多 100 项 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdUsageInfo*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

/**
 * 当天零点，距 2000-01-01 00:00:00 的秒数。
 * 协议增量提案（iOS/Android 同方案，待协议文档与固件确认，plan.md T-9）：
 * 旧固件不下发该字段（值为 0），SDK 退回按分包序号推算日期。
 **/
@property(nonatomic, readwrite) int32_t timestamp;

@end

#pragma mark - TSMetaHsdGameRecord

typedef GPB_ENUM(TSMetaHsdGameRecord_FieldNumber) {
  TSMetaHsdGameRecord_FieldNumber_Timestamp = 1,
  TSMetaHsdGameRecord_FieldNumber_GameType = 2,
  TSMetaHsdGameRecord_FieldNumber_Duration = 3,
  TSMetaHsdGameRecord_FieldNumber_Score = 4,
  TSMetaHsdGameRecord_FieldNumber_Level = 5,
};

/**
 * =============================================================
 * 游戏（0x02-0x66 最高记录 / 0x67 排名趋势）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaHsdGameRecord : GPBMessage

/** 时间戳，距 2000-01-01 00:00:00 的秒数 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 游戏类型（0-24） */
@property(nonatomic, readwrite) int32_t gameType;

/** 游戏时长（秒） */
@property(nonatomic, readwrite) int32_t duration;

/** 得分 */
@property(nonatomic, readwrite) int32_t score;

/** 等级 */
@property(nonatomic, readwrite) int32_t level;

@end

#pragma mark - TSMetaHsdGameRecordList

typedef GPB_ENUM(TSMetaHsdGameRecordList_FieldNumber) {
  TSMetaHsdGameRecordList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaHsdGameRecordList : GPBMessage

/** 游戏记录列表，最多 10 条（0x66 实际最多返回 3 条） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdGameRecord*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaHsdGameRankingTrend

typedef GPB_ENUM(TSMetaHsdGameRankingTrend_FieldNumber) {
  TSMetaHsdGameRankingTrend_FieldNumber_GameType = 1,
  TSMetaHsdGameRankingTrend_FieldNumber_Ranking = 2,
  TSMetaHsdGameRankingTrend_FieldNumber_Trend = 3,
};

GPB_FINAL @interface TSMetaHsdGameRankingTrend : GPBMessage

/** 游戏类型（0-24） */
@property(nonatomic, readwrite) int32_t gameType;

/** 排名，0-255 */
@property(nonatomic, readwrite) int32_t ranking;

/** 趋势：0 下降，1 不变，2 上升 */
@property(nonatomic, readwrite) int32_t trend;

@end

#pragma mark - TSMetaHsdGameRankingTrendList

typedef GPB_ENUM(TSMetaHsdGameRankingTrendList_FieldNumber) {
  TSMetaHsdGameRankingTrendList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaHsdGameRankingTrendList : GPBMessage

/** 游戏排名趋势列表，最多 30 条 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaHsdGameRankingTrend*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
