# -*- coding: utf-8 -*-
"""生成华盛达页面新增的本地化条目（zh-Hans / en / hi），追加到三份 Localizable.strings 末尾。"""
import re, sys, os

# key: (zh, en, hi)
S = {}
def add(k, zh, en, hi): S[k] = (zh, en, hi)

# ---- 通用 ----
add("hsd.bytes_format", "%lu / %lu 字节", "%lu / %lu bytes", "%lu / %lu बाइट")
add("hsd.repeat", "重复", "Repeat", "दोहराव")
add("hsd.none", "无", "None", "कोई नहीं")
add("hsd.limit_reached", "已达上限", "Limit reached", "सीमा पूरी")
add("hsd.remaining_format", "还可添加 %lu 个", "%lu more can be added", "%lu और जोड़ सकते हैं")
add("hsd.sec.device_readonly", "手表维护 · 只读", "Maintained by watch · read-only", "वॉच द्वारा प्रबंधित · केवल पढ़ने योग्य")
add("hsd.loading.watch", "正在读取手表…", "Reading from watch…", "वॉच से पढ़ा जा रहा है…")
add("hsd.unknown_type_format", "未知类型 (%ld)", "Unknown type (%ld)", "अज्ञात प्रकार (%ld)")
add("hsd.unit.minutes", "分钟", "min", "मिनट")
add("hsd.unit.seconds", "秒", "s", "सेकंड")
add("hsd.unit.days", "天", "days", "दिन")
add("hsd.duration.hm_format", "%ld 小时 %ld 分", "%ldh %ldm", "%ld घं %ld मि")
add("hsd.duration.h_format", "%ld 小时", "%ldh", "%ld घंटे")
add("hsd.duration.m_format", "%ld 分钟", "%ld min", "%ld मिनट")
add("hsd.duration.ms_format", "%ld 分 %ld 秒", "%ldm %lds", "%ld मि %ld से")
add("hsd.duration.s_format", "%ld 秒", "%lds", "%ld सेकंड")
add("hsd.time.start", "开始", "Start", "शुरू")
add("hsd.time.end", "结束", "End", "समाप्त")
add("hsd.time.next_day", "次日", "next day", "अगला दिन")
add("hsd.time.hour", "时", "HOUR", "घंटा")
add("hsd.time.minute", "分", "MIN", "मिनट")

# ---- 保存条 / 保存流程 ----
add("hsd.save.to_watch", "保存到手表", "Save to watch", "वॉच में सहेजें")
add("hsd.save.failed", "保存失败", "Save failed", "सहेजना विफल")
add("hsd.send.failed", "发送失败", "Send failed", "भेजना विफल")
add("hsd.save.readback_match", "已保存，回读一致", "Saved · readback matches", "सहेजा गया · रीडबैक मेल खाता है")
add("hsd.save.readback_failed_format", "已下发，但回读失败：%@", "Sent, but readback failed: %@", "भेजा गया, लेकिन रीडबैक विफल: %@")
add("hsd.dock.dirty", "有未保存的修改", "Unsaved changes", "असहेजे बदलाव")
add("hsd.dock.dirty_small", "保存后自动回读校验", "Verified by readback after saving", "सहेजने के बाद रीडबैक से सत्यापन")
add("hsd.dock.saving", "正在保存…", "Saving…", "सहेजा जा रहा है…")
add("hsd.dock.write_only", "只写能力", "Write-only feature", "केवल-लिखने की सुविधा")
add("hsd.dock.offline_save", "未连接，无法保存", "Not connected · cannot save", "कनेक्ट नहीं · सहेज नहीं सकते")
add("hsd.dock.offline_send", "未连接，无法发送", "Not connected · cannot send", "कनेक्ट नहीं · भेज नहीं सकते")
add("hsd.dock.save_all_format", "保存全部 %ld 项", "Save all %ld", "सभी %ld सहेजें")
add("hsd.dock.send_format", "发送 %lu 条", "Send %lu", "%lu भेजें")
add("hsd.dock.last_sent_format", "上次发送 %@", "Last sent %@", "पिछली बार भेजा %@")
add("hsd.dock.never_sent", "尚未发送过", "Never sent", "अभी तक नहीं भेजा")
add("hsd.discard.title", "放弃修改？", "Discard changes?", "बदलाव छोड़ें?")
add("hsd.discard.message", "有未保存到手表的修改，返回后将丢失。", "Changes not saved to the watch will be lost.", "वॉच में न सहेजे गए बदलाव खो जाएंगे।")
add("hsd.reload.title", "重新读取？", "Reload from watch?", "वॉच से फिर पढ़ें?")
add("hsd.reload.message", "读到的结果会覆盖当前未保存的修改。", "The result will overwrite your unsaved changes.", "परिणाम आपके असहेजे बदलावों को बदल देगा।")
add("hsd.reload.confirm", "重新读取", "Reload", "फिर पढ़ें")
add("hsd.write_only.banner_sent_format", "协议没有读取指令。下面是 App 本地缓存的上次发送内容（%@ 发送）。", "The protocol has no read command. Below is the last content sent, cached locally (sent %@).", "प्रोटोकॉल में पढ़ने का आदेश नहीं है। नीचे पिछली बार भेजी गई सामग्री है (भेजा %@)।")
add("hsd.write_only.banner_never", "协议没有读取指令。下面是 App 本地缓存的上次发送内容，目前还没有发送过。", "The protocol has no read command. Below is the locally cached content; nothing has been sent yet.", "प्रोटोकॉल में पढ़ने का आदेश नहीं है। अभी तक कुछ नहीं भेजा गया।")

# ---- 错误 ----
add("hsd.error.not_support", "当前设备不支持该能力", "This device does not support the feature", "यह डिवाइस इस सुविधा का समर्थन नहीं करता")
add("hsd.error.invalid_param", "参数不满足约束，SDK 在发送前已拦截", "Invalid parameter — rejected by the SDK before sending", "अमान्य पैरामीटर — SDK ने भेजने से पहले रोक दिया")
add("hsd.error.set_failed", "手表拒绝了这次设置", "The watch rejected the setting", "वॉच ने सेटिंग अस्वीकार कर दी")
add("hsd.error.get_failed", "读取失败", "Read failed", "पढ़ना विफल")
add("hsd.error.disconnected", "与手表的连接已断开", "Disconnected from the watch", "वॉच से कनेक्शन टूट गया")
add("hsd.error.not_ready", "设备未就绪", "Device not ready", "डिवाइस तैयार नहीं")
add("hsd.error.busy", "设备繁忙，请稍后再试", "Device busy, try again later", "डिवाइस व्यस्त है, बाद में प्रयास करें")
add("hsd.error.timeout", "手表没有响应", "The watch did not respond", "वॉच ने जवाब नहीं दिया")
add("hsd.error.missing_fragments", "手表返回的分包序号不连续，可能跳过了没有使用记录的日期。请把这个现象反馈给固件（用例 D-31）。", "Packet indexes from the watch are not contiguous; days without records may have been skipped. Report to firmware (case D-31).", "वॉच के पैकेट क्रम असंतत हैं; रिकॉर्ड रहित दिन छूट सकते हैं। फ़र्मवेयर को रिपोर्ट करें (केस D-31)।")
add("hsd.error.fragments_title", "分包不连续", "Missing fragments", "पैकेट गायब")
add("hsd.error.minute_range", "时间必须在 00:00–23:59 之间", "Time must be within 00:00–23:59", "समय 00:00–23:59 के बीच होना चाहिए")

# ---- 回读差异 ----
add("hsd.diff.title_format", "回读差异 · %ld 处", "Readback differences · %ld", "रीडबैक अंतर · %ld")
add("hsd.diff.intro", "保存成功，但手表回读的值与刚才下发的不一致。页面已更新为手表上的实际值。", "Saved, but the values read back differ from what was sent. The page now shows the watch's actual values.", "सहेजा गया, लेकिन रीडबैक मान भेजे गए मान से भिन्न हैं। पेज अब वॉच के वास्तविक मान दिखाता है।")
add("hsd.diff.foot", "测试可以直接把这张表贴进缺陷单。", "Testers can paste this table straight into a bug report.", "परीक्षक इस तालिका को सीधे बग रिपोर्ट में चिपका सकते हैं।")
add("hsd.diff.col.field", "字段", "Field", "फ़ील्ड")
add("hsd.diff.col.sent", "下发", "Sent", "भेजा")
add("hsd.diff.col.read", "回读", "Read back", "रीडबैक")
add("hsd.diff.whole_model", "整个模型", "whole model", "पूरा मॉडल")
add("hsd.diff.missing", "（缺失）", "(missing)", "(अनुपस्थित)")

# ---- 日志 ----
add("hsd.log.title", "接口日志", "Call log", "कॉल लॉग")
add("hsd.log.count_format", "%ld 条", "%ld entries", "%ld प्रविष्टियां")
add("hsd.log.empty", "还没有调用记录", "No calls yet", "अभी तक कोई कॉल नहीं")
add("hsd.log.empty_sub", "进入任意功能页后，这里会按时间倒序记录每一次 SDK 调用：方法、参数摘要、结果与耗时。", "Every SDK call made from the feature pages is listed here, newest first: method, arguments, result and duration.", "फ़ीचर पेज से किया गया हर SDK कॉल यहां सूचीबद्ध होगा: विधि, तर्क, परिणाम और अवधि।")
add("hsd.log.pending", "进行中", "in progress", "प्रगति में")
add("hsd.log.ok", "成功", "OK", "ठीक")
add("hsd.log.readback", "回读校验", "readback", "रीडबैक")
add("hsd.log.pre_read", "保存前静默回读", "silent read before save", "सहेजने से पहले मौन पठन")
add("hsd.log.after_exchange", "兑换后重读", "re-read after exchange", "विनिमय के बाद पुनः पठन")
add("hsd.log.hub_summary", "总览摘要", "overview summary", "अवलोकन सारांश")

# ---- 总览 ----
add("hsd.overview.chip", "仅 NPK 实现", "NPK only", "केवल NPK")
add("hsd.overview.summary_failed", "读取失败，进入页面重试", "Read failed, open the page to retry", "पढ़ना विफल, पुनः प्रयास के लिए पेज खोलें")
add("hsd.overview.not_enabled", "未开启", "Off", "बंद")
add("hsd.overview.parental_on_game_format", "<b>已开启</b> · 游戏 %@–%@", "<b>On</b> · games %@–%@", "<b>चालू</b> · गेम %@–%@")
add("hsd.overview.parental_on_nolimit", "<b>已开启</b> · 不限游戏时段", "<b>On</b> · no game window", "<b>चालू</b> · गेम समय सीमा नहीं")
add("hsd.overview.task_format", "<b>%lu</b> 个任务 · <b>%ld</b> 金币", "<b>%lu</b> tasks · <b>%ld</b> coins", "<b>%lu</b> कार्य · <b>%ld</b> सिक्के")
add("hsd.overview.habit_format", "<b>%lu</b> 个习惯 · %lu 个进行中", "<b>%lu</b> habits · %lu ongoing", "<b>%lu</b> आदतें · %lu जारी")
add("hsd.overview.ice_sent_format", "已发送 <b>%lu</b> 条 · %@", "Sent <b>%lu</b> · %@", "<b>%lu</b> भेजे · %@")

# ---- 家长模式 ----
add("hsd.parental.chip", "0x5A 读 · 0x5B 写", "0x5A read · 0x5B write", "0x5A पढ़ें · 0x5B लिखें")
add("hsd.parental.master", "开启家长模式", "Parental mode", "अभिभावक मोड")
add("hsd.parental.master_on", "手表按下面的规则受限", "The watch is restricted by the rules below", "वॉच नीचे के नियमों से सीमित है")
add("hsd.parental.master_off", "已关闭，规则会保留", "Off — rules are kept", "बंद — नियम सुरक्षित रहेंगे")
add("hsd.parental.foot_off", "关闭期间，下面的明细取值原样保留，并随保存一起下发。", "While off, the detail values are kept as-is and sent along when saving.", "बंद होने पर विवरण मान यथावत रहते हैं और सहेजते समय भेजे जाते हैं।")
add("hsd.parental.sec.permissions", "手表上允许的操作", "Allowed on the watch", "वॉच पर अनुमत")
add("hsd.parental.time_setting", "设置时间", "Set time", "समय सेट करना")
add("hsd.parental.time_setting_sub", "允许孩子在手表上改时间", "Allow the child to change the time on the watch", "बच्चे को वॉच पर समय बदलने दें")
add("hsd.parental.enter_setting", "进入设置", "Open settings", "सेटिंग खोलना")
add("hsd.parental.enter_setting_sub", "允许打开手表的设置菜单", "Allow opening the watch settings menu", "वॉच सेटिंग मेनू खोलने दें")
add("hsd.parental.alarm_setting", "设置闹钟", "Set alarms", "अलार्म सेट करना")
add("hsd.parental.alarm_setting_sub", "允许孩子自己增删闹钟", "Allow the child to add or delete alarms", "बच्चे को अलार्म जोड़ने/हटाने दें")
add("hsd.parental.foot_polarity", "开关极性按 SDK 头文件的「允许…」书写，待真机确认（D-12）。", "Switch polarity follows the SDK header (\"allow…\"), to be confirmed on a real device (D-12).", "स्विच ध्रुवता SDK हेडर (\"अनुमति…\") के अनुसार है, वास्तविक डिवाइस पर पुष्टि लंबित (D-12)।")
add("hsd.parental.sec.game", "游戏", "Games", "गेम")
add("hsd.parental.game_limit", "限制游戏时段", "Limit game window", "गेम समय सीमित करें")
add("hsd.parental.game_limit_on", "只有时段内可以玩游戏", "Games only within the window", "केवल समय-सीमा में गेम")
add("hsd.parental.game_limit_off", "全天都可以玩游戏", "Games allowed all day", "पूरे दिन गेम की अनुमति")
add("hsd.parental.timeline_caption", "每天可玩", "Playable per day", "प्रतिदिन खेलने योग्य")
add("hsd.parental.foot_next_day", "结束早于开始表示跨天，时间轴会分成两段；SDK 按分钟偏移原值透传。", "An end earlier than the start spans midnight and the timeline splits in two; the SDK passes the minute offsets through unchanged.", "समाप्ति शुरुआत से पहले होने पर मध्यरात्रि पार होती है; SDK मिनट ऑफ़सेट यथावत भेजता है।")

# ---- 课堂模式 ----
add("hsd.classroom.chip", "0x5C 读 · 0x5D 写", "0x5C read · 0x5D write", "0x5C पढ़ें · 0x5D लिखें")
add("hsd.classroom.master", "开启课堂模式", "Classroom mode", "कक्षा मोड")
add("hsd.classroom.master_on", "时段内手表只保留时间显示", "During the period the watch shows only the time", "अवधि में वॉच केवल समय दिखाती है")
add("hsd.classroom.master_off", "已关闭，时段与重复日会保留", "Off — period and repeat days are kept", "बंद — अवधि और दोहराव दिन सुरक्षित")
add("hsd.classroom.sec.period", "上课时段", "Class period", "कक्षा अवधि")
add("hsd.classroom.timeline_caption", "每天静默", "Silent per day", "प्रतिदिन मौन")
add("hsd.classroom.banner_no_repeat", "没有选择重复日。手表会如何处理由固件决定，SDK 按 0 原值下发。", "No repeat day selected. Firmware decides how the watch behaves; the SDK sends 0 as-is.", "कोई दोहराव दिन नहीं चुना। वॉच का व्यवहार फ़र्मवेयर तय करता है; SDK 0 भेजता है।")
add("hsd.classroom.foot", "位掩码 bit0 = 周一 … bit6 = 周日，复用 TSAlarmRepeat。手表侧修改后没有主动通知，重新进入本页即可读到最新值（D-16）。", "Bitmask bit0 = Monday … bit6 = Sunday (TSAlarmRepeat). The watch does not push changes; re-enter this page to read the latest value (D-16).", "बिटमास्क bit0 = सोमवार … bit6 = रविवार (TSAlarmRepeat)। वॉच बदलाव नहीं भेजती; नवीनतम मान के लिए पेज फिर खोलें (D-16)।")

# ---- 任务 ----
add("hsd.task.chip", "0x5E 读 · 0x5F 写 · 0x60 兑换", "0x5E read · 0x5F write · 0x60 exchange", "0x5E पढ़ें · 0x5F लिखें · 0x60 विनिमय")
add("hsd.task.total_coins", "当前总金币", "Total coins", "कुल सिक्के")
add("hsd.task.adjust", "调整", "Adjust", "समायोजित")
add("hsd.task.exchange", "兑换", "Exchange", "विनिमय")
add("hsd.task.today_done", "今日任务完成", "Done today", "आज पूर्ण")
add("hsd.task.today_earn", "今天还能赚", "Still to earn today", "आज और कमा सकते हैं")
add("hsd.task.coins_unit", "金币", "coins", "सिक्के")
add("hsd.task.pending_format", "%ld 个任务待完成", "%ld tasks pending", "%ld कार्य शेष")
add("hsd.task.sec.tasks", "任务", "Tasks", "कार्य")
add("hsd.task.no_time", "不显示时间", "No time shown", "समय नहीं दिखेगा")
add("hsd.task.empty_title", "还没有任务", "No tasks yet", "अभी कोई कार्य नहीं")
add("hsd.task.empty_text", "给孩子布置第一个每日任务，完成后可以获得金币。", "Assign the first daily task; completing it earns coins.", "पहला दैनिक कार्य दें; पूरा करने पर सिक्के मिलेंगे।")
add("hsd.task.add", "添加任务", "Add task", "कार्य जोड़ें")
add("hsd.task.foot", "当天状态由手表维护，保存时原值带回。任务表整表下发：保存会覆盖手表上的全部任务与总金币。", "Daily state is maintained by the watch and sent back unchanged. The whole task list is sent: saving overwrites all tasks and the total coins on the watch.", "दैनिक स्थिति वॉच रखती है। पूरी कार्य सूची भेजी जाती है: सहेजने पर वॉच के सभी कार्य और कुल सिक्के बदल जाते हैं।")
add("hsd.task.err_count_format", "任务 %lu 条，超过上限 %lu。", "%lu tasks exceed the limit of %lu.", "%lu कार्य सीमा %lu से अधिक हैं।")
add("hsd.task.err_label_format", "第 %lu 个任务的标签超过 %lu 字节。", "Task %lu label exceeds %lu bytes.", "कार्य %lu का लेबल %lu बाइट से अधिक है।")
add("hsd.task.err_desc_format", "第 %lu 个任务的描述超过 %lu 字节。", "Task %lu description exceeds %lu bytes.", "कार्य %lu का विवरण %lu बाइट से अधिक है।")
add("hsd.task.watch_changed", "手表侧数据已变化", "Data changed on the watch", "वॉच पर डेटा बदल गया")
add("hsd.task.change_coins_format", "总金币 %ld → %ld", "Total coins %ld → %ld", "कुल सिक्के %ld → %ld")
add("hsd.task.change_coins_choice", "你也改了总金币，保存时以哪个为准？", "You also changed the total coins. Which one should be saved?", "आपने भी कुल सिक्के बदले हैं। कौन सा सहेजें?")
add("hsd.task.change_overwrite_hint", "直接保存会用旧值覆盖它们。", "Saving now would overwrite them with old values.", "अभी सहेजने पर पुराने मान उन्हें बदल देंगे।")
add("hsd.task.use_mine_format", "用我的 %ld", "Use mine (%ld)", "मेरा (%ld) उपयोग करें")
add("hsd.task.use_watch_format", "用手表的 %ld", "Use watch's (%ld)", "वॉच का (%ld) उपयोग करें")
add("hsd.task.adopt_watch_and_save", "采用手表数据并保存", "Adopt watch data and save", "वॉच डेटा अपनाएं और सहेजें")
add("hsd.task.confirm_save_format", "保存全部 %lu 项到手表？", "Save all %lu tasks to the watch?", "सभी %lu कार्य वॉच में सहेजें?")
add("hsd.task.confirm_save_msg_format", "将整表覆盖手表上的任务，总金币 %ld。", "This replaces all tasks on the watch; total coins %ld.", "यह वॉच के सभी कार्य बदल देगा; कुल सिक्के %ld।")
add("hsd.task.confirm_clear", "清空手表上的全部任务？", "Clear all tasks on the watch?", "वॉच के सभी कार्य साफ़ करें?")
add("hsd.task.confirm_clear_msg_format", "将下发 0 个任务（总金币 %ld），手表是否清空由固件决定。", "0 tasks will be sent (total coins %ld); whether the watch clears is up to firmware.", "0 कार्य भेजे जाएंगे (कुल सिक्के %ld); वॉच साफ़ होगी या नहीं यह फ़र्मवेयर तय करेगा।")
add("hsd.task.exchange_confirm", "兑换奖励？", "Exchange rewards?", "इनाम विनिमय करें?")
add("hsd.task.exchange_confirm_msg_format", "请求手表兑换累计的 %ld 金币，金币如何扣减由固件决定。", "Ask the watch to exchange the %ld accumulated coins; how coins are deducted is decided by firmware.", "वॉच से संचित %ld सिक्कों का विनिमय करने को कहें; कटौती फ़र्मवेयर तय करता है।")
add("hsd.task.exchange_failed", "兑换失败", "Exchange failed", "विनिमय विफल")
add("hsd.task.exchange_watch_rejected", "手表返回兑换失败（success = NO）", "The watch reported exchange failed (success = NO)", "वॉच ने विनिमय विफल बताया (success = NO)")
add("hsd.task.exchange_ok_readback_failed", "兑换已完成，但回读失败", "Exchange completed, but readback failed", "विनिमय पूरा, लेकिन रीडबैक विफल")
add("hsd.task.exchange_ok_format", "兑换完成 · 金币 %ld → %ld", "Exchanged · coins %ld → %ld", "विनिमय पूरा · सिक्के %ld → %ld")
add("hsd.task.new_title", "新任务", "New task", "नया कार्य")
add("hsd.task.edit_title", "编辑任务", "Edit task", "कार्य संपादित करें")
add("hsd.task.watch_tag", "任务", "TASK", "कार्य")
add("hsd.task.watch_coins_format", "+%ld 金币", "+%ld coins", "+%ld सिक्के")
add("hsd.task.type", "类型", "Type", "प्रकार")
add("hsd.task.foot_type", "上方是手表上的示意。类型取值 0–22 由 FitCloud 侧推断、待固件确认；SDK 原值透传。", "Above is a preview of the watch. Type values 0–22 are inferred from FitCloud and pending firmware confirmation; the SDK passes them through.", "ऊपर वॉच का पूर्वावलोकन है। प्रकार मान 0–22 FitCloud से अनुमानित हैं, फ़र्मवेयर पुष्टि लंबित; SDK यथावत भेजता है।")
add("hsd.task.sec.content", "显示内容", "Display", "प्रदर्शन")
add("hsd.task.label", "标签", "Label", "लेबल")
add("hsd.task.label_ph", "可留空（留空时手表显示什么待固件确认）", "Optional (what the watch shows when empty is up to firmware)", "वैकल्पिक (खाली होने पर वॉच क्या दिखाएगी, फ़र्मवेयर तय करेगा)")
add("hsd.task.desc", "详细描述", "Description", "विवरण")
add("hsd.task.desc_ph", "可选", "Optional", "वैकल्पिक")
add("hsd.task.foot_bytes", "上限按 UTF-8 字节计：一个汉字 3 字节，emoji 通常 4 字节。超限时 SDK 会在发送前返回参数错误。", "Limits are in UTF-8 bytes: a CJK character is 3 bytes, an emoji usually 4. Over the limit the SDK returns a parameter error before sending.", "सीमा UTF-8 बाइट में है: एक देवनागरी अक्षर 3 बाइट, इमोजी आमतौर पर 4। सीमा पार होने पर SDK भेजने से पहले त्रुटि देता है।")
add("hsd.task.sec.time", "时间", "Time", "समय")
add("hsd.task.show_time", "在手表上显示时间", "Show time on watch", "वॉच पर समय दिखाएं")
add("hsd.task.show_time_sub", "关闭后手表不显示执行时间", "When off the watch shows no execution time", "बंद होने पर वॉच निष्पादन समय नहीं दिखाती")
add("hsd.task.exec_time", "执行时间", "Time", "समय")
add("hsd.task.sec.reward", "奖励", "Reward", "इनाम")
add("hsd.task.reward_coins", "完成后奖励", "Reward on completion", "पूरा होने पर इनाम")
add("hsd.task.enable", "启用任务", "Enable task", "कार्य सक्षम")
add("hsd.task.id", "任务 ID", "Task ID", "कार्य ID")
add("hsd.task.today_state", "当天状态", "Today's state", "आज की स्थिति")
add("hsd.task.delete", "删除任务", "Delete task", "कार्य हटाएं")
add("hsd.task.delete_confirm", "删除这个任务？", "Delete this task?", "यह कार्य हटाएं?")
add("hsd.task.delete_confirm_msg", "回到列表页保存后才会从手表上移除。", "It is removed from the watch only after saving on the list page.", "सूची पेज पर सहेजने के बाद ही वॉच से हटेगा।")
add("hsd.task.state.0", "未开始", "Not started", "शुरू नहीं")
add("hsd.task.state.1", "进行中", "Ongoing", "जारी")
add("hsd.task.state.2", "已完成", "Completed", "पूर्ण")

# ---- 金币面板 ----
add("hsd.coins.adjust_title", "调整总金币", "Adjust total coins", "कुल सिक्के समायोजित करें")
add("hsd.coins.zero", "清零", "Zero", "शून्य")
add("hsd.coins.sheet_foot", "总金币随任务表一起下发（0x5F 每包都带 totalCoins）。这里改的是草稿，回到列表页保存后才会写入手表。", "Total coins are sent with the task list (every 0x5F packet carries totalCoins). This edits the draft; it is written to the watch after saving on the list page.", "कुल सिक्के कार्य सूची के साथ भेजे जाते हैं (हर 0x5F पैकेट में totalCoins)। यह ड्राफ़्ट है; सूची पेज पर सहेजने के बाद वॉच में लिखा जाएगा।")

# ---- 习惯 ----
add("hsd.habit.chip", "0x61 读 · 0x62 写", "0x61 read · 0x62 write", "0x61 पढ़ें · 0x62 लिखें")
add("hsd.habit.sec.all", "全部习惯", "All habits", "सभी आदतें")
add("hsd.habit.custom_default", "自定义习惯", "Custom habit", "कस्टम आदत")
add("hsd.habit.progress_format", "已达成 <b>%ld</b> / %ld 天 · 最长连续 %ld 天", "Reached <b>%ld</b> / %ld days · best streak %ld days", "<b>%ld</b> / %ld दिन पूरे · सर्वश्रेष्ठ %ld दिन")
add("hsd.habit.past_week", "过去一周", "Past week", "पिछला सप्ताह")
add("hsd.habit.empty_title", "还没有习惯", "No habits yet", "अभी कोई आदत नहीं")
add("hsd.habit.empty_text", "习惯是长期目标，手表每天提醒并记录打卡进度。", "Habits are long-term goals; the watch reminds daily and records check-ins.", "आदतें दीर्घकालिक लक्ष्य हैं; वॉच रोज़ याद दिलाती है और प्रगति दर्ज करती है।")
add("hsd.habit.add", "添加习惯", "Add habit", "आदत जोड़ें")
add("hsd.habit.foot", "圆环是达成进度，右下 7 格是过去一周哪几天达成。进度、状态与达成记录由手表维护，保存时原值带回。", "The ring is progress; the 7 cells show which days of the past week were achieved. Progress, state and records are maintained by the watch and sent back unchanged.", "रिंग प्रगति है; 7 कोष्ठ पिछले सप्ताह के पूरे दिन दिखाते हैं। प्रगति, स्थिति और रिकॉर्ड वॉच रखती है।")
add("hsd.habit.err_count_format", "习惯 %lu 条，超过上限 %lu。", "%lu habits exceed the limit of %lu.", "%lu आदतें सीमा %lu से अधिक हैं।")
add("hsd.habit.err_label_format", "第 %lu 个习惯的标签超过 %lu 字节。", "Habit %lu label exceeds %lu bytes.", "आदत %lu का लेबल %lu बाइट से अधिक है।")
add("hsd.habit.confirm_clear", "清空手表上的全部习惯？", "Clear all habits on the watch?", "वॉच की सभी आदतें साफ़ करें?")
add("hsd.habit.confirm_clear_msg", "将下发 0 条习惯，手表是否清空由固件决定。", "0 habits will be sent; whether the watch clears is up to firmware.", "0 आदतें भेजी जाएंगी; वॉच साफ़ होगी या नहीं फ़र्मवेयर तय करेगा।")
add("hsd.habit.log_send_format", "habits=%lu（每条一包）", "habits=%lu (one packet each)", "habits=%lu (प्रत्येक एक पैकेट)")
add("hsd.habit.new_title", "新习惯", "New habit", "नई आदत")
add("hsd.habit.edit_title", "编辑习惯", "Edit habit", "आदत संपादित करें")
add("hsd.habit.sec.type", "类型", "Type", "प्रकार")
add("hsd.habit.name", "习惯名称", "Habit name", "आदत का नाम")
add("hsd.habit.name_ph", "例如：练琴", "e.g. Practice piano", "जैसे: पियानो अभ्यास")
add("hsd.habit.foot_custom", "自定义类型时名称有效。", "The name applies to the custom type.", "नाम कस्टम प्रकार पर लागू होता है।")
add("hsd.habit.foot_preset", "预置类型由手表显示固定名称，名称字段不下发。", "Preset types show a fixed name on the watch; the name field is not sent.", "प्रीसेट प्रकार वॉच पर निश्चित नाम दिखाते हैं; नाम फ़ील्ड नहीं भेजा जाता।")
add("hsd.habit.sec.plan", "计划", "Plan", "योजना")
add("hsd.habit.exec_time", "执行时间", "Time", "समय")
add("hsd.habit.duration", "每次时长", "Duration", "अवधि")
add("hsd.habit.task_days", "任务天数", "Task days", "कार्य दिन")
add("hsd.habit.task_days_sub", "坚持多少天算完成", "Days to keep before it counts as done", "कितने दिन निभाने पर पूर्ण")
add("hsd.habit.foot_range", "数值范围是 Demo 约定，协议与 SDK 对这些字段没有上限。", "Value ranges are Demo conventions; the protocol and SDK impose no upper limit.", "मान सीमाएं डेमो की परंपरा हैं; प्रोटोकॉल और SDK कोई ऊपरी सीमा नहीं रखते।")
add("hsd.habit.sec.remind", "提醒", "Reminder", "अनुस्मारक")
add("hsd.habit.remind_advance", "提前提醒", "Remind before", "पहले याद दिलाएं")
add("hsd.habit.remind_duration", "提醒时长", "Reminder duration", "अनुस्मारक अवधि")
add("hsd.habit.sec.assoc", "关联功能", "Linked feature", "जुड़ी सुविधा")
add("hsd.habit.foot_assoc", "关联运动后，手表在提醒时可以直接进入运动。", "When linked to workout, the watch can start a workout directly from the reminder.", "वर्कआउट से जोड़ने पर वॉच अनुस्मारक से सीधे वर्कआउट शुरू कर सकती है।")
add("hsd.habit.state", "状态", "State", "स्थिति")
add("hsd.habit.reach_max", "已达成 / 最长达成", "Reached / best", "पूरे / सर्वश्रेष्ठ")
add("hsd.habit.reach_max_format", "%ld 天 / %ld 天", "%ld d / %ld d", "%ld दिन / %ld दिन")
add("hsd.habit.latest", "最近达成", "Last achieved", "अंतिम उपलब्धि")
add("hsd.habit.latest_format", "%ld 月 %ld 日", "%ld/%ld", "%ld/%ld")
add("hsd.habit.id", "习惯 ID", "Habit ID", "आदत ID")
add("hsd.habit.delete", "删除习惯", "Delete habit", "आदत हटाएं")
add("hsd.habit.delete_confirm", "删除这个习惯？", "Delete this habit?", "यह आदत हटाएं?")
add("hsd.habit.delete_confirm_msg", "回到列表页保存后才会从手表上移除。", "It is removed from the watch only after saving on the list page.", "सूची पेज पर सहेजने के बाद ही वॉच से हटेगी।")
add("hsd.habit.type.0", "自定义", "Custom", "कस्टम")
add("hsd.habit.type.1", "运动", "Sport", "खेल")
add("hsd.habit.type.2", "学习", "Study", "अध्ययन")
add("hsd.habit.type.3", "睡眠", "Sleep", "नींद")
add("hsd.habit.state.0", "初始", "Init", "प्रारंभिक")
add("hsd.habit.state.1", "进行中", "Ongoing", "जारी")
add("hsd.habit.state.2", "已完成", "Completed", "पूर्ण")
add("hsd.habit.state.3", "已过期", "Overdue", "समय-सीमा पार")
add("hsd.habit.state.4", "已关闭", "Closed", "बंद")
add("hsd.habit.state.5", "已删除", "Deleted", "हटाया गया")
add("hsd.habit.assoc.0", "无", "None", "कोई नहीं")
add("hsd.habit.assoc.1", "运动", "Workout", "वर्कआउट")
# 习惯数值滚轮
add("hsd.unit.hours", "小时", "h", "घंटे")
add("hsd.days_format", "%ld 天", "%ld days", "%ld दिन")
add("hsd.habit.duration_hint", "范围 1 分钟 – 10 小时", "Range 1 min – 10 h", "सीमा 1 मिनट – 10 घंटे")
add("hsd.habit.weeks_format", "约 %@ 周", "≈ %@ weeks", "लगभग %@ सप्ताह")
add("hsd.habit.remind_on_time", "准时", "On time", "समय पर")
add("hsd.habit.remind_advance_hint_zero", "到执行时间时提醒", "Remind at the scheduled time", "निर्धारित समय पर याद दिलाएं")
add("hsd.habit.remind_advance_hint_format", "执行时间前 %ld 分钟提醒", "Remind %ld min before", "%ld मिनट पहले याद दिलाएं")
add("hsd.habit.remind_duration_hint_format", "手表提醒持续 %@", "Watch alert lasts %@", "वॉच अलर्ट %@ तक चलेगा")

# ---- 使用统计 ----
add("hsd.usage.chip", "0x63 应用 · 0x64 游戏 · 0x65 重置", "0x63 apps · 0x64 games · 0x65 reset", "0x63 ऐप · 0x64 गेम · 0x65 रीसेट")
add("hsd.usage.app", "应用", "Apps", "ऐप")
add("hsd.usage.game", "游戏", "Games", "गेम")
add("hsd.usage.app_unit", "个应用", "apps", "ऐप")
add("hsd.usage.game_unit", "个游戏", "games", "गेम")
add("hsd.usage.empty_title", "设备暂无统计数据", "No statistics on the device", "डिवाइस पर कोई आंकड़े नहीं")
add("hsd.usage.empty_text_format", "接口返回空数组。可能是刚重置过，或手表还没有产生%@使用记录。", "The interface returned an empty array. It may have just been reset, or the watch has no %@ usage records yet.", "इंटरफ़ेस ने खाली सूची दी। शायद अभी रीसेट हुआ है, या वॉच में %@ उपयोग रिकॉर्ड नहीं हैं।")
add("hsd.usage.sec.date", "日期", "Date", "तारीख")
add("hsd.usage.kept_days_format", "设备保留 %lu 天", "%lu days kept on device", "डिवाइस पर %lu दिन")
add("hsd.usage.today", "今天", "Today", "आज")
add("hsd.usage.yesterday", "昨天", "Yesterday", "कल")
add("hsd.usage.source.device", "设备日期", "device date", "डिवाइस तारीख")
add("hsd.usage.source.inferred", "推算日期", "inferred date", "अनुमानित तारीख")
add("hsd.usage.banner_inferred", "日期由手机当天减去 dayOffset 推算。手表时间不准、跨零点或跨时区时可能差一天；dayOffset 才是权威值。", "Dates are inferred from the phone's date minus dayOffset. They may be off by one day if the watch time is wrong or across midnight / time zones; dayOffset is authoritative.", "तारीखें फ़ोन की तारीख से dayOffset घटाकर अनुमानित हैं। वॉच समय गलत होने या समय-क्षेत्र बदलने पर एक दिन का अंतर हो सकता है; dayOffset ही प्रामाणिक है।")
add("hsd.usage.empty_day_title", "这一天没有使用记录", "No usage on this day", "इस दिन कोई उपयोग नहीं")
add("hsd.usage.empty_day_text", "设备用空包为这一天占位，所以日期序号仍然连续。", "The device sends an empty packet as a placeholder, so day indexes stay contiguous.", "डिवाइस खाली पैकेट भेजता है, इसलिए दिन क्रम निरंतर रहता है।")
add("hsd.usage.times_unit", "次使用", "uses", "उपयोग")
add("hsd.usage.side_format", "%lu %@\n最常用 <b>%@</b>", "%lu %@\nmost used <b>%@</b>", "%lu %@\nसबसे अधिक <b>%@</b>")
add("hsd.usage.sec.sorted", "按次数排序", "Sorted by count", "गिनती के अनुसार")
add("hsd.usage.foot_count", "次数是当天累计值。重复拉取会得到相同的几天，落库时按（日期，类型）覆盖，不要累加。", "Counts are cumulative per day. Repeated fetches return the same days; persist by (date, type) with overwrite, never accumulate.", "गिनती प्रति दिन संचयी है। बार-बार लाने पर वही दिन मिलते हैं; (तारीख, प्रकार) से अधिलेखित करें, जोड़ें नहीं।")
add("hsd.usage.reset", "重置使用统计", "Reset usage statistics", "उपयोग आंकड़े रीसेट करें")
add("hsd.usage.reset_confirm", "重置使用统计？", "Reset usage statistics?", "उपयोग आंकड़े रीसेट करें?")
add("hsd.usage.reset_confirm_msg", "将清空设备保留的天数。是否同时清空应用与游戏两类由固件决定，重置后会自动重新读取两类并汇报。", "Clears the days kept on the device. Whether apps and games are cleared together is up to firmware; both will be re-read and reported afterwards.", "डिवाइस पर रखे दिन साफ़ होंगे। ऐप और गेम साथ साफ़ होंगे या नहीं फ़र्मवेयर तय करता है; बाद में दोनों फिर पढ़े जाएंगे।")
add("hsd.usage.reset_failed", "重置失败", "Reset failed", "रीसेट विफल")
add("hsd.usage.reset_report_format", "应用：%@ / 游戏：%@", "Apps: %@ / Games: %@", "ऐप: %@ / गेम: %@")
add("hsd.usage.cleared", "已清空", "cleared", "साफ़")
add("hsd.usage.still_days_format", "仍有 %lu 天数据", "still %lu days", "अभी भी %lu दिन")
add("hsd.usage.foot_reset", "重置后设备清空已保留的天数。是否同时清空应用与游戏两类由固件决定，Demo 会在重置后自动重新读取两类并汇报结果。", "After reset the device clears the kept days. Whether apps and games are cleared together is up to firmware; the Demo re-reads both and reports.", "रीसेट के बाद डिवाइस रखे दिन साफ़ करता है। ऐप और गेम साथ साफ़ होंगे या नहीं फ़र्मवेयर तय करता है; डेमो दोनों फिर पढ़कर रिपोर्ट करता है।")

# ---- 游戏 ----
add("hsd.game.chip", "0x66 读记录 · 0x67 写趋势", "0x66 read records · 0x67 write trends", "0x66 रिकॉर्ड पढ़ें · 0x67 रुझान लिखें")
add("hsd.game.tab.records", "最高记录", "Top records", "शीर्ष रिकॉर्ड")
add("hsd.game.tab.trends", "排名趋势", "Ranking trends", "रैंकिंग रुझान")
add("hsd.game.no_record_title", "这个游戏还没有记录", "No records for this game", "इस गेम का कोई रिकॉर्ड नहीं")
add("hsd.game.no_record_text", "接口返回空数组，没有错误。", "The interface returned an empty array without error.", "इंटरफ़ेस ने बिना त्रुटि खाली सूची दी।")
add("hsd.game.records_right_format", "%lu 条 · 设备返回顺序", "%lu · device order", "%lu · डिवाइस क्रम")
add("hsd.game.score_unit", "分", "pts", "अंक")
add("hsd.game.record_meta_format", "用时 %@ · %ld 月 %ld 日", "%@ · %ld/%ld", "%@ · %ld/%ld")
add("hsd.game.records_foot", "设备最多返回 3 条。Demo 按设备返回的顺序展示，不在 App 侧重新排序。", "The device returns at most 3 records. The Demo shows them in device order without re-sorting.", "डिवाइस अधिकतम 3 रिकॉर्ड देता है। डेमो उन्हें डिवाइस क्रम में दिखाता है।")
add("hsd.game.sec.trends", "排名与趋势", "Ranking & trend", "रैंकिंग और रुझान")
add("hsd.game.rank_prefix", "第", "#", "#")
add("hsd.game.rank_unit", "名", "", "")
add("hsd.game.trends_empty_title", "还没有排名数据", "No ranking data", "कोई रैंकिंग डेटा नहीं")
add("hsd.game.trends_empty_text", "添加游戏并填写排名与趋势，发送后手表的游戏页会显示名次和箭头。", "Add games with ranking and trend; after sending, the watch's game page shows the rank and arrow.", "गेम जोड़कर रैंकिंग और रुझान भरें; भेजने के बाद वॉच का गेम पेज रैंक और तीर दिखाता है।")
add("hsd.game.add_game", "添加游戏", "Add game", "गेम जोड़ें")
add("hsd.game.fill_25", "填充 25 个", "Fill all 25", "25 भरें")
add("hsd.game.trends_foot", "排名 0–255；趋势分下降、不变、上升。每条一包，最多 30 条。「填充 25 个」是为用例 D-36 准备的测试数据。", "Ranking 0–255; trend is down / flat / up. One packet per item, at most 30. \"Fill all 25\" generates test data for case D-36.", "रैंकिंग 0–255; रुझान नीचे / स्थिर / ऊपर। प्रति आइटम एक पैकेट, अधिकतम 30। \"25 भरें\" केस D-36 के लिए परीक्षण डेटा बनाता है।")
add("hsd.game.trends_empty_send", "至少添加 1 条排名趋势", "Add at least 1 ranking trend", "कम से कम 1 रैंकिंग रुझान जोड़ें")
add("hsd.game.trends_sent_format", "已发送 %lu 条排名趋势", "Sent %lu ranking trends", "%lu रैंकिंग रुझान भेजे")
add("hsd.trend.0", "降", "Down", "नीचे")
add("hsd.trend.1", "平", "Flat", "स्थिर")
add("hsd.trend.2", "升", "Up", "ऊपर")

# ---- ICE ----
add("hsd.ice.chip", "0x59 只写", "0x59 write-only", "0x59 केवल-लिखें")
add("hsd.ice.label_format", "标签 %lu", "Label %lu", "लेबल %lu")
add("hsd.ice.ph_format", "例如：%@", "e.g. %@", "जैसे: %@")
add("hsd.ice.ph1", "妈妈 138 0000 0000", "Mom 138 0000 0000", "मां 138 0000 0000")
add("hsd.ice.ph2", "过敏：青霉素", "Allergy: penicillin", "एलर्जी: पेनिसिलिन")
add("hsd.ice.ph3", "血型 O", "Blood type O", "रक्त समूह O")
add("hsd.ice.watch_placeholder", "紧急信息会显示在这里", "Emergency info appears here", "आपातकालीन जानकारी यहां दिखेगी")
add("hsd.ice.need_one", "至少填写 1 条", "Fill in at least 1", "कम से कम 1 भरें")
add("hsd.ice.last_sent_resend_format", "上次发送 %@ · 可原样重发", "Last sent %@ · can be re-sent as-is", "पिछली बार भेजा %@ · यथावत पुनः भेज सकते हैं")
add("hsd.ice.sent_format", "已发送 %lu 条 ICE 标签", "Sent %lu ICE labels", "%lu ICE लेबल भेजे")
add("hsd.ice.foot", "ICE（In Case of Emergency）显示在手表的紧急信息页。每条 UTF-8 不超过 63 字节，可以包含 emoji；留空的行不会下发。SDK 不允许下发空数组（TSERROR_INVALID_PARAM），协议没有「清空」指令，如需清空请与固件确认。", "ICE (In Case of Emergency) is shown on the watch's emergency page. Each label is at most 63 UTF-8 bytes and may contain emoji; empty rows are not sent. The SDK rejects an empty array (TSERROR_INVALID_PARAM) and the protocol has no clear command — confirm with firmware if clearing is needed.", "ICE (आपातकाल में) वॉच के आपातकालीन पेज पर दिखता है। प्रत्येक लेबल अधिकतम 63 UTF-8 बाइट, इमोजी संभव; खाली पंक्तियां नहीं भेजी जातीं। SDK खाली सूची अस्वीकार करता है (TSERROR_INVALID_PARAM) और प्रोटोकॉल में साफ़ करने का आदेश नहीं है।")

# ---- 边界工具 ----
add("hsd.tools.chip", "真机用例辅助", "real-device test aid", "वास्तविक-डिवाइस परीक्षण सहायक")
add("hsd.tools.banner", "这些调用预期会被 SDK 在发送前拦截，或用来观察固件的容错。它们不该出现在正常界面里，但真机用例需要跑。", "These calls are expected to be rejected by the SDK before sending, or observe firmware tolerance. They do not belong in the normal UI, but real-device cases need them.", "इन कॉल को SDK भेजने से पहले रोकेगा, या फ़र्मवेयर सहिष्णुता देखने के लिए हैं। ये सामान्य UI में नहीं होते, पर वास्तविक-डिवाइस केस को चाहिए।")
add("hsd.tools.sec.params", "参数越界", "Out-of-range parameters", "सीमा से बाहर पैरामीटर")
add("hsd.tools.sec.stress", "并发与压力", "Concurrency & stress", "समवर्ती और दबाव")
add("hsd.tools.case_format", "用例 %@", "Case %@", "केस %@")
add("hsd.tools.run", "运行", "Run", "चलाएं")
add("hsd.tools.running", "运行中…", "Running…", "चल रहा है…")
add("hsd.tools.six_tasks", "下发 6 个任务", "Send 6 tasks", "6 कार्य भेजें")
add("hsd.tools.eleven_habits", "下发 11 个习惯", "Send 11 habits", "11 आदतें भेजें")
add("hsd.tools.label33", "任务标签 33 字节", "Task label of 33 bytes", "33 बाइट का कार्य लेबल")
add("hsd.tools.four_ice", "下发 4 条 ICE 标签", "Send 4 ICE labels", "4 ICE लेबल भेजें")
add("hsd.tools.ranking256", "排名 ranking = 256", "ranking = 256", "ranking = 256")
add("hsd.tools.trends31", "下发 31 条排名趋势", "Send 31 ranking trends", "31 रैंकिंग रुझान भेजें")
add("hsd.tools.ice64", "ICE 单条 64 字节", "ICE label of 64 bytes", "64 बाइट का ICE लेबल")
add("hsd.tools.zero", "下发 0 条 ICE / 0 条排名趋势", "Send 0 ICE labels / 0 trends", "0 ICE लेबल / 0 रुझान भेजें")
add("hsd.tools.concurrent", "并发读取习惯与使用统计", "Concurrent fetch of habits and usage", "आदतें और उपयोग एक साथ पढ़ें")
add("hsd.tools.parental20", "连续 20 次家长模式读写", "20 consecutive parental mode read/writes", "अभिभावक मोड 20 बार लगातार पढ़ें/लिखें")
add("hsd.tools.intercepted", "已拦截 · 未发送蓝牙包", "Intercepted · no BLE packet sent", "रोका गया · कोई BLE पैकेट नहीं")
add("hsd.tools.not_intercepted_format", "⚠ SDK 未拦截，已发送到手表（success）· %.0f ms", "⚠ Not intercepted by the SDK, sent to the watch (success) · %.0f ms", "⚠ SDK ने नहीं रोका, वॉच को भेजा गया (success) · %.0f ms")
add("hsd.tools.not_intercepted_short", "⚠ 未拦截（success）", "⚠ not intercepted (success)", "⚠ नहीं रोका (success)")
add("hsd.tools.concurrent_tag", "并发", "concurrent", "समवर्ती")
add("hsd.tools.loop_result_format", "成功 %ld · 失败 %ld · 共 %.0f ms · 最后错误 %@", "ok %ld · failed %ld · total %.0f ms · last error %@", "सफल %ld · विफल %ld · कुल %.0f ms · अंतिम त्रुटि %@")

# ---- 家长模式 · 进阶版（parental control，NPK） ----
add("hsd.parental.basic_chip", "基础版 · 开关 + 游戏时段", "Basic · switches + game hours", "बेसिक · स्विच + गेम समय")
add("hsd.pc.chip", "进阶版 · 按功能与时段", "Advanced · per action & period", "एडवांस्ड · क्रिया व अवधि अनुसार")
add("hsd.pc.master_on", "下面启用的功能项按时段受控", "Enabled items below are controlled by period", "नीचे सक्षम आइटम अवधि अनुसार नियंत्रित")
add("hsd.pc.master_off", "已关闭，功能项会保留", "Off · items are kept", "बंद · आइटम रखे गए हैं")
add("hsd.pc.foot_off", "关闭期间，下面的功能项原样保留，并随保存一起下发。", "While off, the items below are kept as they are and sent together on save.", "बंद रहने पर नीचे के आइटम वैसे ही रखे जाते हैं और सहेजते समय साथ भेजे जाते हैं।")
add("hsd.pc.sec.items", "受控功能", "Controlled actions", "नियंत्रित क्रियाएं")
add("hsd.pc.configured_format", "%ld / %ld 项已配置", "%ld / %ld configured", "%ld / %ld कॉन्फ़िगर")
add("hsd.pc.item.unset", "未设置", "Not set", "सेट नहीं")
add("hsd.pc.item.off", "已关闭", "Off", "बंद")
add("hsd.pc.no_period", "无时段", "No period", "कोई अवधि नहीं")
add("hsd.pc.period_count_format", "%ld 个时段", "%ld periods", "%ld अवधियां")
add("hsd.pc.all_day", "全天", "All day", "पूरा दिन")
add("hsd.pc.foot_items", "点一项进入编辑：开关、时段内的行为与最多 %ld 个生效时段。每次保存下发完整列表，手表整体替换。", "Tap an item to edit its switch, in-period behaviour and up to %ld periods. Every save sends the whole list and the watch replaces its configuration.", "स्विच, अवधि-व्यवहार और अधिकतम %ld अवधियां संपादित करने के लिए आइटम टैप करें। हर सेव पूरी सूची भेजता है और वॉच अपनी सेटिंग बदल देती है।")
add("hsd.pc.err_duplicate_format", "「%@」重复出现", "\"%@\" appears more than once", "\"%@\" एक से अधिक बार है")
add("hsd.pc.err_period_count_format", "「%@」有 %ld 个时段，超过上限 %ld", "\"%@\" has %ld periods, over the limit of %ld", "\"%@\" में %ld अवधियां हैं, सीमा %ld से अधिक")
add("hsd.pc.edit.sec.item", "功能项", "Item", "आइटम")
add("hsd.pc.edit.enabled", "启用此项", "Enable this item", "यह आइटम सक्षम करें")
add("hsd.pc.edit.enabled_on", "按下面的时段控制", "Controlled by the periods below", "नीचे की अवधियों से नियंत्रित")
add("hsd.pc.edit.enabled_off", "不控制，时段仅保留", "Not controlled · periods are kept", "नियंत्रित नहीं · अवधियां रखी गईं")
add("hsd.pc.edit.sec.mode", "时段内的行为", "Behaviour inside the periods", "अवधि के भीतर व्यवहार")
add("hsd.pc.edit.foot_mode_disable", "时段内禁止该操作，时段外允许。", "The action is blocked inside the periods and allowed outside.", "क्रिया अवधि के भीतर अवरुद्ध और बाहर अनुमत।")
add("hsd.pc.edit.foot_mode_allow", "只有时段内允许该操作，时段外禁止。", "The action is allowed only inside the periods and blocked outside.", "क्रिया केवल अवधि के भीतर अनुमत और बाहर अवरुद्ध।")
add("hsd.pc.edit.sec.periods", "生效时段", "Periods", "अवधियां")
add("hsd.pc.edit.period_title_format", "时段 %ld", "Period %ld", "अवधि %ld")
add("hsd.pc.edit.timeline_caption", "生效", "Active", "सक्रिय")
add("hsd.pc.edit.add_period", "添加时段", "Add period", "अवधि जोड़ें")
add("hsd.pc.edit.remove_period", "删除", "Remove", "हटाएं")
add("hsd.pc.edit.empty_title", "还没有时段", "No periods yet", "अभी कोई अवधि नहीं")
add("hsd.pc.edit.empty_text", "没有时段时，本项不会在任何时间生效。", "Without periods this item never takes effect.", "अवधि के बिना यह आइटम कभी प्रभावी नहीं होगा।")
add("hsd.pc.edit.foot_periods", "开始与结束相同表示全天；结束早于开始表示跨天，以起始日为准。", "Same start and end means all day; an end before the start crosses midnight and counts on the start day.", "समान शुरू/समाप्त = पूरा दिन; शुरू से पहले समाप्त = आधी रात पार, शुरू के दिन गिना जाता है।")
add("hsd.pc.edit.remove_item", "从列表移除此功能项", "Remove this item from the list", "इस आइटम को सूची से हटाएं")
add("hsd.pc.edit.remove_item_confirm", "移除功能项？", "Remove item?", "आइटम हटाएं?")
add("hsd.pc.edit.remove_item_msg", "该功能项及其时段将从列表移除，保存后手表按剩余列表生效。", "The item and its periods are removed from the list; after saving the watch uses the remaining list.", "आइटम और उसकी अवधियां सूची से हटेंगी; सहेजने के बाद वॉच शेष सूची उपयोग करेगी।")
add("hsd.overview.pc_on_format", "<b>已开启</b> · %ld 项受控", "<b>On</b> · %ld controlled", "<b>चालू</b> · %ld नियंत्रित")
add("hsd.overview.pc_on_none", "<b>已开启</b> · 未启用功能项", "<b>On</b> · no item enabled", "<b>चालू</b> · कोई आइटम सक्षम नहीं")
PC_FUNC_ZH = ["", "长按换表盘", "进入游戏", "进入计算器", "进入任务", "进入时间日期", "进入音乐控制", "进入设置", "修改闹钟"]
PC_FUNC_EN = ["", "Change watch face", "Enter games", "Enter calculator", "Enter tasks", "Enter date & time", "Enter music control", "Enter settings", "Modify alarms"]
PC_FUNC_HI = ["", "वॉच फ़ेस बदलें", "गेम खोलें", "कैलकुलेटर खोलें", "कार्य खोलें", "तारीख व समय खोलें", "संगीत नियंत्रण खोलें", "सेटिंग खोलें", "अलार्म बदलें"]
for i in range(1, 9): add("hsd.pc.func.%d" % i, PC_FUNC_ZH[i], PC_FUNC_EN[i], PC_FUNC_HI[i])
add("hsd.pc.mode.0", "时段内禁用", "Blocked in period", "अवधि में अवरुद्ध")
add("hsd.pc.mode.1", "时段内允许", "Allowed in period", "अवधि में अनुमत")

# ---- 内容枚举：应用 48 ----
APPS_ZH = ["无","当天数据","心率","闹钟","游戏","睡眠","日期时间","ICE","习惯","运动记录","血压","血氧","计算器","天气","秒表","音乐","亮屏调节","息屏时钟","切换表盘","亮屏时长","翻腕亮屏时长","语言设置","勿扰","震动","健康检测","单位设置","日期设置","时间设置","电池","喝水","久坐","左右手佩戴","关机","番茄闹钟","用户指南","二维码","密码","拨号","常用联系人","通话记录","语音助手","运动","消息通知","女性健康","呼吸训练","相机","查找手机","下键设置"]
APPS_EN = ["None","Daily data","Heart rate","Alarm","Games","Sleep","Date & time","ICE","Habits","Sport records","Blood pressure","Blood oxygen","Calculator","Weather","Stopwatch","Music","Brightness","Screen-off clock","Watch face","Screen-on time","Wrist-raise time","Language","Do not disturb","Vibration","Health check","Units","Date settings","Time settings","Battery","Drink water","Sedentary","Wearing hand","Power off","Pomodoro","User guide","QR code","Password","Dialer","Contacts","Call log","Voice assistant","Workout","Notifications","Female health","Breathing","Camera","Find phone","Down key"]
APPS_HI = ["कोई नहीं","दैनिक डेटा","हृदय गति","अलार्म","गेम","नींद","तारीख व समय","ICE","आदतें","खेल रिकॉर्ड","रक्तचाप","रक्त ऑक्सीजन","कैलकुलेटर","मौसम","स्टॉपवॉच","संगीत","चमक","स्क्रीन-ऑफ़ घड़ी","वॉच फ़ेस","स्क्रीन-ऑन समय","कलाई उठाने का समय","भाषा","परेशान न करें","कंपन","स्वास्थ्य जांच","इकाइयां","तारीख सेटिंग","समय सेटिंग","बैटरी","पानी पिएं","लंबे समय बैठना","पहनने का हाथ","बंद करें","पोमोडोरो","उपयोगकर्ता गाइड","QR कोड","पासवर्ड","डायलर","संपर्क","कॉल लॉग","वॉइस सहायक","वर्कआउट","सूचनाएं","महिला स्वास्थ्य","श्वास","कैमरा","फ़ोन खोजें","नीचे की कुंजी"]
assert len(APPS_ZH) == 48 and len(APPS_EN) == 48 and len(APPS_HI) == 48
for i in range(48): add("hsd.app.%d" % i, APPS_ZH[i], APPS_EN[i], APPS_HI[i])

# ---- 内容枚举：游戏 25 ----
GAMES_ZH = ["宠物养成","2048","糖果消消乐","拼图","飞机","赛车","迷宫","篮球","算数题","俄罗斯方块","数独","答题","跳一跳","堆堆乐","连一连","贪吃蛇","24 点","糖果跳跳","弹球突破","3 分投篮","足球靶子","可爱方块","五子连珠","打小鸟","五彩太空砖"]
GAMES_EN = ["Pet raising","2048","Candy crush","Puzzle","Airplane","Racing","Maze","Basketball","Arithmetic","Tetris","Sudoku","Quiz","Jump","Stacking","Connect","Snake","24 points","Candy jump","Breakout","Three-point shot","Soccer target","Cute blocks","Gomoku","Hit the bird","Space bricks"]
GAMES_HI = ["पालतू पालन","2048","कैंडी क्रश","पहेली","हवाई जहाज़","रेसिंग","भूलभुलैया","बास्केटबॉल","अंकगणित","टेट्रिस","सुडोकु","क्विज़","जंप","स्टैकिंग","कनेक्ट","सांप","24 अंक","कैंडी जंप","ब्रेकआउट","थ्री-पॉइंट शॉट","सॉकर लक्ष्य","प्यारे ब्लॉक","गोमोकु","चिड़िया मारो","स्पेस ब्रिक्स"]
assert len(GAMES_ZH) == 25 and len(GAMES_EN) == 25 and len(GAMES_HI) == 25
for i in range(25): add("hsd.gametype.%d" % i, GAMES_ZH[i], GAMES_EN[i], GAMES_HI[i])

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def block(lang_index, header):
    lines = ["", "", "// ===== 华盛达定制 · 功能页（自动生成于 gen_strings.py） =====" if lang_index == 0 else "", ""]
    lines = ["", "// ===== Huashengda feature pages (%s) =====" % header]
    for k in S:
        lines.append('"%s" = "%s";' % (k, esc(S[k][lang_index])))
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    for i, name in enumerate(["zh-Hans", "en", "hi"]):
        with open(os.path.join(out, "hsd_%s.strings" % name), "w", encoding="utf-8") as f:
            f.write(block(i, name))
    print(len(S), "keys")
