#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "TSAIChatConfig.h"
#import "TSAIChatContent.h"
#import "TSAIChatEvent.h"
#import "TSAIChatIntent.h"
#import "TSAIChatReport.h"
#import "TSAISummaryPartialResult.h"
#import "TSAISummaryResult.h"
#import "TSAIAssistantDefines.h"
#import "TSAIAssistantInterface.h"
#import "TSAudioRecordBlocks.h"
#import "TSAudioRecordDefines.h"
#import "TSAudioRecordInterface.h"
#import "TSAIAudioRecordConfig.h"
#import "TSAIAudioRecordSessionResult.h"
#import "TSAIAudioRecordSpeakerSegment.h"
#import "TSAIContractDefines.h"
#import "TSAIDefines.h"
#import "TSAILanguageMapper.h"
#import "TSAIFeatureDefines.h"
#import "TSAIFeatureInterface.h"
#import "TSAIImageGenerationDefines.h"
#import "TSAIImageGenerationInterface.h"
#import "TSAIImageGenerationConfig.h"
#import "TSAIImageGenerationResult.h"
#import "TSAIImageGenerationStyle.h"
#import "TSAIInterpreterConfig.h"
#import "TSAIInterpreterContent.h"
#import "TSAIInterpreterEvent.h"
#import "TSAIInterpreterReport.h"
#import "TSAIInterpreterUtterance.h"
#import "TSAIInterpreterDefines.h"
#import "TSAIInterpreterInterface.h"
#import "TSAIQuestionAnswerDefines.h"
#import "TSAIQuestionAnswerInterface.h"
#import "TSAIQuestionAnswerConfig.h"
#import "TSAIQuestionAnswerPartialResult.h"
#import "TSAIQuestionAnswerResult.h"
#import "TSAISpeechDefines.h"
#import "TSAISpeechInterface.h"
#import "TSAIASRDeviceMicConfig.h"
#import "TSAIASRDeviceMicResult.h"
#import "TSAIASRFileConfig.h"
#import "TSAIASRPartialResult.h"
#import "TSAIASRPCMConfig.h"
#import "TSAIASRResult.h"
#import "TSAITTSConfig.h"
#import "TSAITTSResult.h"
#import "TSAITTSStreamChunk.h"
#import "TSAITranslateDefines.h"
#import "TSAITranslateInterface.h"
#import "TSAITranslateConfig.h"
#import "TSAITranslatePartialResult.h"
#import "TSAITranslateResult.h"
#import "TSAIContext.h"
#import "TSAIContextConfiguration.h"
#import "TSAIContextDefines.h"
#import "TSAIKit.h"
#import "TSAIDeviceBridge.h"
#import "TSAIDeviceBridgeEventSink.h"
#import "TSAIDeviceQuestionAnswerOutputSink.h"
#import "TSAIDeviceVoiceTranslationOutputSink.h"
#import "TSAIKitAssistantAdapter.h"
#import "TSAIKitAudioRecordAdapter.h"
#import "TSAIKitImageGenerationAdapter.h"
#import "TSAIKitInterpreterAdapter.h"
#import "TSAIKitQuestionAnswerAdapter.h"
#import "TSAIKitSpeechAdapter.h"
#import "TSAIKitTextTranslateAdapter.h"
#import "TSAIAssistantProvider.h"
#import "TSAIAudioRecordProvider.h"
#import "TSAIImageGenerationProvider.h"
#import "TSAIInterpreterProvider.h"
#import "TSAIProvider.h"
#import "TSAIQuestionAnswerProvider.h"
#import "TSAISpeechProvider.h"
#import "TSAITranslateProvider.h"
#import "TSAIDeviceBridgeRegistry.h"
#import "TSAIProviderRegistry.h"
#import "TopStepAIKit.h"
#import "TopStepAIKitCore.h"
#import "TopStepAIKitAdapter.h"
#import "TSAIContext+AIBudsAuthentication.h"
#import "TSMltCloudDevice.h"
#import "TSStarBurstDevice.h"
#import "TSAIBudsConfiguration.h"
#import "TSAIBudsManager.h"
#import "TSAIKitErrorMapper.h"
#import "TSAIKitModelMapper.h"
#import "TSAIBudsAssistantProvider.h"
#import "TSAIBudsAudioRecordProvider.h"
#import "TSAIBudsImageGenerationProvider.h"
#import "TSAIBudsInterpreterProvider.h"
#import "TSAIBudsProvider.h"
#import "TSAIBudsQuestionAnswerProvider.h"
#import "TSAIBudsSpeechProvider.h"
#import "TSAIBudsTranslateProvider.h"
#import "TSAIBudsSessionStore.h"

FOUNDATION_EXPORT double TopStepAIKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepAIKitVersionString[];

