// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: pb_connect_param.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TSMetaPeripheralLimits;
@class TSMetaPeripheralShape;
@class TSMetaTimeModel;
@class TSMetaUserModel;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbConnectParamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PbConnectParamRoot : GPBRootObject
@end

#pragma mark - TSMetaAuthParam

typedef GPB_ENUM(TSMetaAuthParam_FieldNumber) {
  TSMetaAuthParam_FieldNumber_UserId = 1,
  TSMetaAuthParam_FieldNumber_System = 2,
  TSMetaAuthParam_FieldNumber_Version = 3,
  TSMetaAuthParam_FieldNumber_Brand = 4,
  TSMetaAuthParam_FieldNumber_Model = 5,
  TSMetaAuthParam_FieldNumber_AuthCode = 6,
  TSMetaAuthParam_FieldNumber_User = 7,
  TSMetaAuthParam_FieldNumber_Time = 8,
};

/**
 * =============================================================
 * BLE 连接参数总模型
 * =============================================================
 **/
GPB_FINAL @interface TSMetaAuthParam : GPBMessage

/** 用户ID（英文或数字，后端用于关联用户） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 系统类型：0=iOS, 1=Android */
@property(nonatomic, readwrite) int32_t system;

/** 系统版本号，如 17.5.1 / 14.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** 手机品牌，例如: Apple / Samsung */
@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

/** 手机型号，例如: iPhone 15 Pro / SM‑G9910 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** 设备/用户配对验证码或授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *authCode;

/** 用户信息（性别/年龄/身高/体重） */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaUserModel *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** 时间信息（当前时间戳、时区） */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaTimeModel *time;
/** Test to see if @c time has been set. */
@property(nonatomic, readwrite) BOOL hasTime;

@end

#pragma mark - TSMetaUserModel

typedef GPB_ENUM(TSMetaUserModel_FieldNumber) {
  TSMetaUserModel_FieldNumber_Gender = 1,
  TSMetaUserModel_FieldNumber_Age = 2,
  TSMetaUserModel_FieldNumber_Height = 3,
  TSMetaUserModel_FieldNumber_Weight = 4,
};

/**
 * =============================================================
 * 用户信息模型
 * =============================================================
 **/
GPB_FINAL @interface TSMetaUserModel : GPBMessage

/** 性别：0=女性, 1=男性 */
@property(nonatomic, readwrite) uint32_t gender;

/** 年龄（岁） */
@property(nonatomic, readwrite) uint32_t age;

/** 身高（厘米） */
@property(nonatomic, readwrite) uint32_t height;

/** 体重（千克） */
@property(nonatomic, readwrite) float weight;

@end

#pragma mark - TSMetaTimeModel

typedef GPB_ENUM(TSMetaTimeModel_FieldNumber) {
  TSMetaTimeModel_FieldNumber_Timestamp = 1,
  TSMetaTimeModel_FieldNumber_ZoneOffset = 2,
};

/**
 * =============================================================
 * 时间信息模型
 * =============================================================
 **/
GPB_FINAL @interface TSMetaTimeModel : GPBMessage

/** 自 2000-01-01 00:00:00 起的 UTC 秒数 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 时区偏移（秒），正数表示东区，负数表示西区 */
@property(nonatomic, readwrite) int32_t zoneOffset;

@end

#pragma mark - TSMetaAuthRespond

typedef GPB_ENUM(TSMetaAuthRespond_FieldNumber) {
  TSMetaAuthRespond_FieldNumber_Result = 1,
  TSMetaAuthRespond_FieldNumber_EverBind = 2,
  TSMetaAuthRespond_FieldNumber_BindTime = 3,
};

/**
 * =============================================================
 * BLE 连接响应模型
 * =============================================================
 **/
GPB_FINAL @interface TSMetaAuthRespond : GPBMessage

/**
 * *
 * 0：表示成功
 * 1：失败，不匹配的userId，仅出现在login模式
 * 2：失败，用户取消了绑定，仅出现在bind模式
 * 3：失败，用户长时间无响应，绑定超时，仅出现在bind模式
 * 4：IOS13以下的情况，等效于绑定成功（0的状态），但经典蓝牙未连接
 * 5：手环电量不足，无法删除数据。
 * 6：手环正在恢复出厂。
 * 7：需要用户去操作恢复出厂，设备才允许重新被绑定
 * 127：失败，未知.
 **/
@property(nonatomic, readwrite) int32_t result;

/**
 * *
 * 仅在绑定成功时，这个值才有意义。否则忽略这个值。
 * 0：代表第一次绑定
 * 1：之前已经绑定过
 **/
@property(nonatomic, readwrite) int32_t everBind;

/**
 * *
 * 这个用户首次绑定的时间戳（秒）。
 * 通常用于判断手表此次绑定是否清除了数据
 * 仅在绑定/登录成功时，这个值才有意义。否则忽略这个值。
 **/
@property(nonatomic, readwrite) int64_t bindTime;

@end

#pragma mark - TSMetaBatteryModel

typedef GPB_ENUM(TSMetaBatteryModel_FieldNumber) {
  TSMetaBatteryModel_FieldNumber_Level = 1,
  TSMetaBatteryModel_FieldNumber_Charging = 2,
};

/**
 * =============================================================
 * 电池信息
 * =============================================================
 **/
GPB_FINAL @interface TSMetaBatteryModel : GPBMessage

/** 电量百分比(1~100) */
@property(nonatomic, readwrite) uint32_t level;

/** 是否充电中：false=未充电，true=充电中 */
@property(nonatomic, readwrite) BOOL charging;

@end

#pragma mark - TSMetaLanguageModel

typedef GPB_ENUM(TSMetaLanguageModel_FieldNumber) {
  TSMetaLanguageModel_FieldNumber_Language = 1,
};

/**
 * =============================================================
 * 语言配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaLanguageModel : GPBMessage

/** 语言代号 */
@property(nonatomic, readwrite) int32_t language;

@end

#pragma mark - TSMetaLanguageList

typedef GPB_ENUM(TSMetaLanguageList_FieldNumber) {
  TSMetaLanguageList_FieldNumber_Items = 1,
};

/**
 * 语言列表，长度64字节，每个字节代表一种语言
 **/
GPB_FINAL @interface TSMetaLanguageList : GPBMessage

/** max_size=64 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *items;

@end

#pragma mark - TSMetaAppStatusModel

typedef GPB_ENUM(TSMetaAppStatusModel_FieldNumber) {
  TSMetaAppStatusModel_FieldNumber_IsForeground = 1,
  TSMetaAppStatusModel_FieldNumber_PermissionSms = 2,
  TSMetaAppStatusModel_FieldNumber_PermissionLocation = 3,
};

/**
 * =============================================================
 * APP状态信息
 * =============================================================
 **/
GPB_FINAL @interface TSMetaAppStatusModel : GPBMessage

/** 是否前台，0否，1是 */
@property(nonatomic, readwrite) int32_t isForeground;

/** 是否有短信权限，0否，1是 */
@property(nonatomic, readwrite) int32_t permissionSms;

/** 是否有定位权限，0否，1是 */
@property(nonatomic, readwrite) int32_t permissionLocation;

@end

#pragma mark - TSMetaPeripheralShape

typedef GPB_ENUM(TSMetaPeripheralShape_FieldNumber) {
  TSMetaPeripheralShape_FieldNumber_Shape = 1,
  TSMetaPeripheralShape_FieldNumber_Width = 2,
  TSMetaPeripheralShape_FieldNumber_Height = 3,
  TSMetaPeripheralShape_FieldNumber_Corners = 4,
};

/**
 * =============================================================
 * 外形尺寸与设备信息
 * =============================================================
 **/
GPB_FINAL @interface TSMetaPeripheralShape : GPBMessage

/** 形状：0=方形，1=圆形 */
@property(nonatomic, readwrite) int32_t shape;

/** 宽度 */
@property(nonatomic, readwrite) int32_t width;

/** 高度 */
@property(nonatomic, readwrite) int32_t height;

/** 圆角 */
@property(nonatomic, readwrite) int32_t corners;

@end

#pragma mark - TSMetaPeripheralInfo

typedef GPB_ENUM(TSMetaPeripheralInfo_FieldNumber) {
  TSMetaPeripheralInfo_FieldNumber_Project = 1,
  TSMetaPeripheralInfo_FieldNumber_Version = 2,
  TSMetaPeripheralInfo_FieldNumber_Brand = 3,
  TSMetaPeripheralInfo_FieldNumber_Model = 4,
  TSMetaPeripheralInfo_FieldNumber_Serial = 5,
  TSMetaPeripheralInfo_FieldNumber_MainBoard = 6,
  TSMetaPeripheralInfo_FieldNumber_Shape = 7,
  TSMetaPeripheralInfo_FieldNumber_Ability = 8,
  TSMetaPeripheralInfo_FieldNumber_Activity = 9,
  TSMetaPeripheralInfo_FieldNumber_SleepAlgorithm = 10,
  TSMetaPeripheralInfo_FieldNumber_Preview = 11,
  TSMetaPeripheralInfo_FieldNumber_Limits = 12,
  TSMetaPeripheralInfo_FieldNumber_Notifications = 13,
};

/**
 * =============================================================
 * 设备信息（基础能力与限制）
 * =============================================================
 **/
GPB_FINAL @interface TSMetaPeripheralInfo : GPBMessage

/** 项目号，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *project;

/** 版本号，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** 品牌，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

/** 型号，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** 序列号，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serial;

/** 主板号，max-len=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mainBoard;

/** 外形尺寸 */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaPeripheralShape *shape;
/** Test to see if @c shape has been set. */
@property(nonatomic, readwrite) BOOL hasShape;

/** 设备能力，max-size=16 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *ability;

/** 活动记录配置，max-size=3 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *activity;

/** 睡眠数据处理，0默认，跟项目相关 */
@property(nonatomic, readwrite) int32_t sleepAlgorithm;

/** 预览外形尺寸 */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaPeripheralShape *preview;
/** Test to see if @c preview has been set. */
@property(nonatomic, readwrite) BOOL hasPreview;

/** 部分限制 */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaPeripheralLimits *limits;
/** Test to see if @c limits has been set. */
@property(nonatomic, readwrite) BOOL hasLimits;

/** 是否支持某个Flag的通知，max-size=8 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *notifications;

@end

#pragma mark - TSMetaPeripheralLimits

typedef GPB_ENUM(TSMetaPeripheralLimits_FieldNumber) {
  TSMetaPeripheralLimits_FieldNumber_BuiltInDial = 1,
  TSMetaPeripheralLimits_FieldNumber_CloudDial = 2,
  TSMetaPeripheralLimits_FieldNumber_Alarm = 3,
  TSMetaPeripheralLimits_FieldNumber_Contact = 4,
  TSMetaPeripheralLimits_FieldNumber_RemindArray = 5,
};

/**
 * =============================================================
 * 限制配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaPeripheralLimits : GPBMessage

/** 内置表盘最大数量 */
@property(nonatomic, readwrite) int32_t builtInDial;

/** 云端表盘最大数量 */
@property(nonatomic, readwrite) int32_t cloudDial;

/** 闹钟最大数量 */
@property(nonatomic, readwrite) int32_t alarm;

/** 联系人最大数量 */
@property(nonatomic, readwrite) int32_t contact;

/** max-count=8 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *remindArray;
/** The number of items in @c remindArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger remindArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
