#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "PbCommonParam.pbobjc.h"
#import "PbConfigParam.pbobjc.h"
#import "PbConnectParam.pbobjc.h"
#import "PbDataParam.pbobjc.h"
#import "PbSettingParam.pbobjc.h"
#import "PbSportDetail.pbobjc.h"
#import "PbStreamParam.pbobjc.h"
#import "TSMetaBase.h"
#import "TSMetaBaseModel.h"
#import "TSMetaAlarm.h"
#import "TSMetaAppStatus.h"
#import "TSMetaBattery.h"
#import "TSMetaAuthParam+Extensions.h"
#import "TSMetaBleConnect.h"
#import "TSMetaBleConnectDefines.h"
#import "TSBleConnectOption.h"
#import "TSBleManager.h"
#import "TSBleScanPeripheralParam.h"
#import "TSBleMetaKit.h"
#import "TSBusinessBase.h"
#import "TSMetaCamera.h"
#import "TSMetaContact.h"
#import "TSMetaDailyActivity.h"
#import "TSMetaBaseDataSync.h"
#import "TSMetaBODataSync.h"
#import "TSMetaBPDataSync.h"
#import "TSMetaDailyActDataSync.h"
#import "TSMetaECGDataSync.h"
#import "TSMetaHRDataSync.h"
#import "TSMetaSleepDataSync.h"
#import "TSMetaSportDataSync.h"
#import "TSMetaStressDataSync.h"
#import "TSMetaTempDataSync.h"
#import "TSMetaDataSync.h"
#import "TSMetaHealthData.h"
#import "TSMetaHealthDataDefines.h"
#import "TSMetaSyncStartRequest+meta.h"
#import "TSSportDetailParser.h"
#import "TSMetaFemaleHealth.h"
#import "TSFileTransferDefines.h"
#import "TSMetaFileData+Extension.h"
#import "TSMetaFileDataResponse+Extension.h"
#import "TSMetaFileHeadResponse+Extension.h"
#import "TSMetaFileReceiver.h"
#import "TSMetaFileSender.h"
#import "TSMetaFileTransfer.h"
#import "TSMetaFileValidator.h"
#import "TSMetaLanguage.h"
#import "TSMetaMeasure.h"
#import "TSMetaMonitor.h"
#import "TSMetaMusic.h"
#import "TSMetaNotification.h"
#import "TSMetaPeripheralFind.h"
#import "TSMetaPrayers.h"
#import "TSMetaReminder.h"
#import "TSMetaRemoteControl.h"
#import "TSMetaSetting.h"
#import "TSMetaTime.h"
#import "TSMetaUnit.h"
#import "TSMetaUserInfo.h"
#import "TSMetaWatchFace.h"
#import "TSMetaWeather.h"
#import "TSMetaWeatherDefines.h"
#import "TSMetaWorldClock.h"
#import "TSCmdDataReceiver.h"
#import "TSCommand.h"
#import "TSCommandBase.h"
#import "TSCommandDefines.h"
#import "TSCommandRequest.h"
#import "TSCommandDataParser.h"
#import "TSCommandDataTool.h"
#import "TSCommandDataWrapper.h"
#import "TSDataSendManager.h"
#import "TSPackageHandleInterface.h"
#import "TSParsedPacket.h"
#import "TSBleMetaKitOption.h"
#import "TSRequestManager.h"
#import "TSRequestOption.h"
#import "TSRequestNotifyManager.h"
#import "TopStepBleMetaKit.h"
#import "TSMetaTools.h"

FOUNDATION_EXPORT double TopStepBleMetaKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepBleMetaKitVersionString[];

