#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "TSAlarmClockModel+Fw.h"
#import "TSFwAlarmClock.h"
#import "TSBatteryModel+Fw.h"
#import "TSFwBattery.h"
#import "TSFwBleConnect.h"
#import "TSFwBleConnectHelper.h"
#import "TSPeripheral+Fw.h"
#import "TSPeripheralInfoService.h"
#import "TSFwCamera.h"
#import "TSFwComDataStorage.h"
#import "TSFwComKit.h"
#import "TSContactModel+Fw.h"
#import "TSFwContact.h"
#import "TSFwBaseDataSync.h"
#import "TSBOValueModel+Fw.h"
#import "TSFwBODataSync.h"
#import "TSBPValueModel+Fw.h"
#import "TSFwBPDataSync.h"
#import "TSDailyActivityValueModel+Fw.h"
#import "TSFwDailyExerciseDataSync.h"
#import "TSFwEgcDataSync.h"
#import "TSFwHRDataSync.h"
#import "TSHRValueModel+Fw.h"
#import "TSSleepConcreteModel+Fw.h"
#import "TSSleepItemModel+Fw.h"
#import "TSSleepModel+Fw.h"
#import "TSSleepNapModel+Fw.h"
#import "TSSleepSummaryModel+Fw.h"
#import "TSFwSleepDataSync.h"
#import "TSFwSportDataSync.h"
#import "TSSportItemModel+Fw.h"
#import "TSSportModel+Fw.h"
#import "TSSportSummaryModel+Fw.h"
#import "TSFwStressDataSync.h"
#import "TSStressValueModel+Fw.h"
#import "TSFwTempDataSync.h"
#import "TSTemperatureValueModel+Fw.h"
#import "TSFwDataSync.h"
#import "TSECardModel+Fw.h"
#import "TSFwECardBag.h"
#import "TSFwFileOTA.h"
#import "TSFwGlasses.h"
#import "TSFwBloodOxygen.h"
#import "TSBPAutoMonitorConfigs+Fw.h"
#import "TSFwBloodPressure.h"
#import "TSDailyActivityGoalsModel+Fw.h"
#import "TSFwExerciseGoals.h"
#import "TSFwDailyActivity.h"
#import "TSFwElectrocardio.h"
#import "TSActivityMeasureParam+Fw.h"
#import "TSFwActiveMeasure.h"
#import "TSAutoMonitorConfigs+Fw.h"
#import "TSFwAutoMonitor.h"
#import "TSFwHealthBase.h"
#import "TSHRAutoMonitorConfigs+Fw.h"
#import "TSFwHeartRate.h"
#import "TSFwSleep.h"
#import "TSFwSport.h"
#import "TSFwStress.h"
#import "TSFwTemperature.h"
#import "TSFwKitBase.h"
#import "TSFwKitInit.h"
#import "TSFwLanguage.h"
#import "TSLanguageModel+Fw.h"
#import "TSFwMessage.h"
#import "TSMessageModel+Fw.h"
#import "TSFwDialModel+Fw.h"
#import "TSFwPeripheralDial.h"
#import "TSFwPeripheralFind.h"
#import "TSFwReminders.h"
#import "TSRemindersModel+Fw.h"
#import "TSFwRemoteControl.h"
#import "TSDoNotDisturbModel+Fw.h"
#import "TSFwSetting.h"
#import "TSWristWakeUpModel+Fw.h"
#import "TSFwTime.h"
#import "TSFwUnit.h"
#import "TSFwUserInfo.h"
#import "TSUserInfoModel+Fw.h"
#import "TSFwWeather.h"
#import "TSWeatherCode+Fw.h"
#import "TSWeatherDayModel+Fw.h"
#import "TSWeatherHourModel+Fw.h"
#import "TSWeatherModel+Fw.h"
#import "TSFwWorldClock.h"
#import "TSWorldClockModel+Fw.h"
#import "TSCommonCmd.h"
#import "TSCommandConfig.h"
#import "TSMessageObserver.h"
#import "TSObserverObject.h"

FOUNDATION_EXPORT double TopStepPersimwearKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepPersimwearKitVersionString[];

