#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "TSAlarmClockModel+Fw.h"
#import "TSFwAlarmClock.h"
#import "TSApplicationModel+Fw.h"
#import "TSFwAppStore.h"
#import "TSBatteryModel+Fw.h"
#import "TSFwBattery.h"
#import "TSFwBleConnect.h"
#import "TSFwBleConnectHelper.h"
#import "TSPeripheral+Fw.h"
#import "TSPeripheralInfoRequest.h"
#import "TSFwCamera.h"
#import "TSFwComDataStorage.h"
#import "TSFwComKit.h"
#import "TopStepContactModel+Fw.h"
#import "TSFwContact.h"
#import "TSFwBaseDataSync.h"
#import "TSBOValueItem+Fw.h"
#import "TSFwBODataSync.h"
#import "TSBPValueItem+Fw.h"
#import "TSFwBPDataSync.h"
#import "TSDailyActivityItem+Fw.h"
#import "TSFwDailyExerciseDataSync.h"
#import "TSFwEgcDataSync.h"
#import "TSFwHRDataSync.h"
#import "TSHRValueItem+Fw.h"
#import "TSSleepDailyModel+Fw.h"
#import "TSSleepDetailItem+Fw.h"
#import "TSFwSleepDataSync.h"
#import "TSFwSportDataSync.h"
#import "TSSportItemModel+Fw.h"
#import "TSSportModel+Fw.h"
#import "TSSportSummaryModel+Fw.h"
#import "TSFwStressDataSync.h"
#import "TSStressValueItem+Fw.h"
#import "TSFwTempDataSync.h"
#import "TSTempValueItem+Fw.h"
#import "TSFwDataSync.h"
#import "TSDataSyncConfig+Fw.h"
#import "TSFwHealthData.h"
#import "TSECardModel+Fw.h"
#import "TSFwECardBag.h"
#import "TSFemaleHealthConfig+Fw.h"
#import "TSFwFemaleHealth.h"
#import "TSFwFileOTA.h"
#import "TSFwGlasses.h"
#import "TSFwBloodOxygen.h"
#import "TSAutoMonitorBPConfigs+Fw.h"
#import "TSFwBloodPressure.h"
#import "TSDailyActivityGoals+Fw.h"
#import "TSFwExerciseGoals.h"
#import "TSFwDailyActivity.h"
#import "TSFwElectrocardio.h"
#import "TSActivityMeasureParam+Fw.h"
#import "TSFwActiveMeasure.h"
#import "TSAutoMonitorConfigs+Fw.h"
#import "TSFwAutoMonitor.h"
#import "TSFwHealthBase.h"
#import "TSAutoMonitorHRConfigs+Fw.h"
#import "TSFwHeartRate.h"
#import "TSFwSleep.h"
#import "TSFwSport.h"
#import "TSFwStress.h"
#import "TSFwTemperature.h"
#import "TSFwKitBase.h"
#import "TSFwKitInit.h"
#import "TSFwLanguage.h"
#import "TSLanguageModel+Fw.h"
#import "TSFwMessage.h"
#import "TSMessageModel+Fw.h"
#import "TSFwMusic.h"
#import "TSDialModel+Fw.h"
#import "TSFwPeripheralDial.h"
#import "TSFwPeripheralFind.h"
#import "TSFwPrayers.h"
#import "TSPrayerConfigs+Fw.h"
#import "TSPrayerTimes+Fw.h"
#import "TSFwReminders.h"
#import "TSRemindersModel+Fw.h"
#import "TSFwRemoteControl.h"
#import "TSDoNotDisturbModel+Fw.h"
#import "TSFwSetting.h"
#import "TSWristWakeUpModel+Fw.h"
#import "TSFwTime.h"
#import "TSFwUnit.h"
#import "TSFwUserInfo.h"
#import "TSUserInfoModel+Fw.h"
#import "TopStepWeather+Fw.h"
#import "TSFwWeather.h"
#import "TSWeatherCodeModel+Fw.h"
#import "TSWeatherDay+Fw.h"
#import "TSWeatherHour+Fw.h"
#import "TSFwWorldClock.h"
#import "TSWorldClockModel+Fw.h"
#import "TSCommonCmd.h"
#import "TSCommandConfig.h"
#import "TSMessageObserver.h"
#import "TSObserverObject.h"

FOUNDATION_EXPORT double TopStepPersimwearKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepPersimwearKitVersionString[];

