// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: pb_setting_param.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TSMetaAlarmItem;
@class TSMetaContactItem;
@class TSMetaDialItem;
@class TSMetaPrayerTimes;
@class TSMetaRemindItem;
@class TSMetaReminderDndModel;
@class TSMetaWeatherDayModel;
@class TSMetaWeatherHourModel;
@class TSMetaWorldClockItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbSettingParamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PbSettingParamRoot : GPBRootObject
@end

#pragma mark - TSMetaCameraActionModel

typedef GPB_ENUM(TSMetaCameraActionModel_FieldNumber) {
  TSMetaCameraActionModel_FieldNumber_Action = 1,
};

/**
 * =============================================================
 * 相机控制
 * =============================================================
 **/
GPB_FINAL @interface TSMetaCameraActionModel : GPBMessage

/** 操作类型：0=退出相机，1=进入相机，2=拍照，3=切换后置摄像头，4=切换前置摄像头，5=闪光关，6=闪光自动，7=闪光开 */
@property(nonatomic, readwrite) int32_t action;

@end

#pragma mark - TSMetaAlarmItem

typedef GPB_ENUM(TSMetaAlarmItem_FieldNumber) {
  TSMetaAlarmItem_FieldNumber_Id_p = 1,
  TSMetaAlarmItem_FieldNumber_IsEnabled = 2,
  TSMetaAlarmItem_FieldNumber_Hour = 3,
  TSMetaAlarmItem_FieldNumber_Minute = 4,
  TSMetaAlarmItem_FieldNumber_Repeat = 5,
  TSMetaAlarmItem_FieldNumber_Label = 6,
};

/**
 * =============================================================
 * 闹钟配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaAlarmItem : GPBMessage

/** 闹钟ID */
@property(nonatomic, readwrite) int32_t id_p;

/** 是否启用 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 小时，取值范围 0-23 */
@property(nonatomic, readwrite) int32_t hour;

/** 分钟，取值范围 0-59 */
@property(nonatomic, readwrite) int32_t minute;

/** 重复设置，位掩码，从低到高位分别表示周一到周日 (bit0=周一, bit6=周日) */
@property(nonatomic, readwrite) int32_t repeat;

/** 闹钟名称，最大长度 63 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@end

#pragma mark - TSMetaAlarmList

typedef GPB_ENUM(TSMetaAlarmList_FieldNumber) {
  TSMetaAlarmList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaAlarmList : GPBMessage

/** 闹钟列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaAlarmItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaContactItem

typedef GPB_ENUM(TSMetaContactItem_FieldNumber) {
  TSMetaContactItem_FieldNumber_Name = 1,
  TSMetaContactItem_FieldNumber_Phone = 2,
};

/**
 * =============================================================
 * 联系人配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaContactItem : GPBMessage

/** 联系人名称，最大长度 31 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 联系人电话，最大长度 31 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@end

#pragma mark - TSMetaContactList

typedef GPB_ENUM(TSMetaContactList_FieldNumber) {
  TSMetaContactList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaContactList : GPBMessage

/** 联系人列表，最大数量 14 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaContactItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaContactEmergencyList

typedef GPB_ENUM(TSMetaContactEmergencyList_FieldNumber) {
  TSMetaContactEmergencyList_FieldNumber_IsEnabled = 1,
  TSMetaContactEmergencyList_FieldNumber_ItemsArray = 2,
};

GPB_FINAL @interface TSMetaContactEmergencyList : GPBMessage

/** 是否启用紧急联系人功能 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 紧急联系人列表，最大数量 14 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaContactItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaReminderDndModel

typedef GPB_ENUM(TSMetaReminderDndModel_FieldNumber) {
  TSMetaReminderDndModel_FieldNumber_IsEnabled = 1,
  TSMetaReminderDndModel_FieldNumber_Start = 2,
  TSMetaReminderDndModel_FieldNumber_End = 3,
};

/**
 * =============================================================
 * 提醒配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaReminderDndModel : GPBMessage

/** 是否启用免打扰 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 开始时间，距离0点的分钟数 */
@property(nonatomic, readwrite) int32_t start;

/** 结束时间，距离0点的分钟数 */
@property(nonatomic, readwrite) int32_t end;

@end

#pragma mark - TSMetaRemindItem

typedef GPB_ENUM(TSMetaRemindItem_FieldNumber) {
  TSMetaRemindItem_FieldNumber_Id_p = 1,
  TSMetaRemindItem_FieldNumber_IsEnabled = 2,
  TSMetaRemindItem_FieldNumber_Name = 3,
  TSMetaRemindItem_FieldNumber_Note = 4,
  TSMetaRemindItem_FieldNumber_Dnd = 5,
  TSMetaRemindItem_FieldNumber_Mode = 6,
  TSMetaRemindItem_FieldNumber_TimesArray = 7,
  TSMetaRemindItem_FieldNumber_Start = 8,
  TSMetaRemindItem_FieldNumber_End = 9,
  TSMetaRemindItem_FieldNumber_Interval = 10,
  TSMetaRemindItem_FieldNumber_Repeat = 11,
};

GPB_FINAL @interface TSMetaRemindItem : GPBMessage

/** 提醒ID，0=久坐提醒，1=喝水提醒，2=吃药提醒，[0-31]是预定义类型，自定义提醒从32开始 */
@property(nonatomic, readwrite) int32_t id_p;

/** 是否启用 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 提醒名称，最大长度 32 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 提醒备注，最大长度 64 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *note;

/** 免打扰设置 */
@property(nonatomic, readwrite, strong, null_resettable) TSMetaReminderDndModel *dnd;
/** Test to see if @c dnd has been set. */
@property(nonatomic, readwrite) BOOL hasDnd;

/** 提醒模式，0=按次数，1=按周期 */
@property(nonatomic, readwrite) int32_t mode;

/** 当mode=0时，每次提醒时间点，最大数量 10 个 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *timesArray;
/** The number of items in @c timesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger timesArray_Count;

/** 当mode=1时，开始时间，距离0点的分钟数 */
@property(nonatomic, readwrite) int32_t start;

/** 当mode=1时，结束时间，距离0点的分钟数 */
@property(nonatomic, readwrite) int32_t end;

/** 当mode=1时，间隔时间（分钟） */
@property(nonatomic, readwrite) int32_t interval;

/** 重复设置，位掩码，从低到高位分别表示周一到周日 */
@property(nonatomic, readwrite) int32_t repeat;

@end

#pragma mark - TSMetaRemindList

typedef GPB_ENUM(TSMetaRemindList_FieldNumber) {
  TSMetaRemindList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaRemindList : GPBMessage

/** 提醒列表，最大数量 10 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaRemindItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaWeatherDayModel

typedef GPB_ENUM(TSMetaWeatherDayModel_FieldNumber) {
  TSMetaWeatherDayModel_FieldNumber_Timestamp = 1,
  TSMetaWeatherDayModel_FieldNumber_Code = 2,
  TSMetaWeatherDayModel_FieldNumber_Type = 3,
  TSMetaWeatherDayModel_FieldNumber_TempMin = 4,
  TSMetaWeatherDayModel_FieldNumber_TempMax = 5,
  TSMetaWeatherDayModel_FieldNumber_CodeN = 6,
  TSMetaWeatherDayModel_FieldNumber_TypeN = 7,
};

/**
 * =============================================================
 * 天气配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaWeatherDayModel : GPBMessage

/** 时间戳，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 天气类别(大分类) */
@property(nonatomic, readwrite) int32_t code;

/** 天气类型(小类型) */
@property(nonatomic, readwrite) int32_t type;

/** 最低温度 */
@property(nonatomic, readwrite) int32_t tempMin;

/** 最高温度 */
@property(nonatomic, readwrite) int32_t tempMax;

/** 天气类别-夜间(大分类) */
@property(nonatomic, readwrite) int32_t codeN;

/** 天气类型-夜间(小类型) */
@property(nonatomic, readwrite) int32_t typeN;

@end

#pragma mark - TSMetaWeatherHourModel

typedef GPB_ENUM(TSMetaWeatherHourModel_FieldNumber) {
  TSMetaWeatherHourModel_FieldNumber_Timestamp = 1,
  TSMetaWeatherHourModel_FieldNumber_Code = 2,
  TSMetaWeatherHourModel_FieldNumber_Type = 3,
  TSMetaWeatherHourModel_FieldNumber_TempCurrent = 4,
  TSMetaWeatherHourModel_FieldNumber_CodeN = 5,
  TSMetaWeatherHourModel_FieldNumber_TypeN = 6,
};

GPB_FINAL @interface TSMetaWeatherHourModel : GPBMessage

/** 时间戳，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 天气类别(大分类) */
@property(nonatomic, readwrite) int32_t code;

/** 天气类型(小类型) */
@property(nonatomic, readwrite) int32_t type;

/** 当前温度 */
@property(nonatomic, readwrite) int32_t tempCurrent;

/** 天气类别-夜间(大分类) */
@property(nonatomic, readwrite) int32_t codeN;

/** 天气类型-夜间(小类型) */
@property(nonatomic, readwrite) int32_t typeN;

@end

#pragma mark - TSMetaWeatherModel

typedef GPB_ENUM(TSMetaWeatherModel_FieldNumber) {
  TSMetaWeatherModel_FieldNumber_City = 1,
  TSMetaWeatherModel_FieldNumber_UpdateTime = 2,
  TSMetaWeatherModel_FieldNumber_Code = 3,
  TSMetaWeatherModel_FieldNumber_TempMin = 4,
  TSMetaWeatherModel_FieldNumber_TempMax = 5,
  TSMetaWeatherModel_FieldNumber_TempCurrent = 6,
  TSMetaWeatherModel_FieldNumber_Pressure = 7,
  TSMetaWeatherModel_FieldNumber_Quality = 8,
  TSMetaWeatherModel_FieldNumber_Humidity = 9,
  TSMetaWeatherModel_FieldNumber_Ultraviolet = 10,
  TSMetaWeatherModel_FieldNumber_WindAngle = 11,
  TSMetaWeatherModel_FieldNumber_WindScale = 12,
  TSMetaWeatherModel_FieldNumber_WindSpeed = 13,
  TSMetaWeatherModel_FieldNumber_Visibility = 14,
  TSMetaWeatherModel_FieldNumber_Type = 15,
  TSMetaWeatherModel_FieldNumber_FutureDaysArray = 16,
  TSMetaWeatherModel_FieldNumber_FutureHoursArray = 17,
  TSMetaWeatherModel_FieldNumber_CodeN = 18,
  TSMetaWeatherModel_FieldNumber_TypeN = 19,
  TSMetaWeatherModel_FieldNumber_Sunrise = 20,
  TSMetaWeatherModel_FieldNumber_Sunset = 21,
};

GPB_FINAL @interface TSMetaWeatherModel : GPBMessage

/** 城市名称，最大长度 32 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

/** 更新时间，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t updateTime;

/** 天气类别(大分类) */
@property(nonatomic, readwrite) int32_t code;

/** 最低温度 */
@property(nonatomic, readwrite) int32_t tempMin;

/** 最高温度 */
@property(nonatomic, readwrite) int32_t tempMax;

/** 当前温度 */
@property(nonatomic, readwrite) int32_t tempCurrent;

/** 气压 */
@property(nonatomic, readwrite) int32_t pressure;

/** 空气质量 */
@property(nonatomic, readwrite) int32_t quality;

/** 湿度 */
@property(nonatomic, readwrite) int32_t humidity;

/** 紫外线 */
@property(nonatomic, readwrite) int32_t ultraviolet;

/** 风向 */
@property(nonatomic, readwrite) float windAngle;

/** 风力 */
@property(nonatomic, readwrite) int32_t windScale;

/** 风速 */
@property(nonatomic, readwrite) float windSpeed;

/** 能见度 */
@property(nonatomic, readwrite) float visibility;

/** 天气类型(小类型) */
@property(nonatomic, readwrite) int32_t type;

/** 未来天气列表，最大数量 7 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaWeatherDayModel*> *futureDaysArray;
/** The number of items in @c futureDaysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger futureDaysArray_Count;

/** 未来天气列表，最大数量 24 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaWeatherHourModel*> *futureHoursArray;
/** The number of items in @c futureHoursArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger futureHoursArray_Count;

/** 天气类别-夜间(大分类) */
@property(nonatomic, readwrite) int32_t codeN;

/** 天气类型-夜间(小类型) */
@property(nonatomic, readwrite) int32_t typeN;

/** 日出时间，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t sunrise;

/** 日落时间，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t sunset;

@end

#pragma mark - TSMetaDataChanged

typedef GPB_ENUM(TSMetaDataChanged_FieldNumber) {
  TSMetaDataChanged_FieldNumber_Type = 1,
};

/**
 * =============================================================
 * 数据变更通知
 * =============================================================
 **/
GPB_FINAL @interface TSMetaDataChanged : GPBMessage

/** 变更类型：0=保留不使用，1=闹钟变更，2=表盘变更，3=祈祷配置变更 */
@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - TSMetaDialItem

typedef GPB_ENUM(TSMetaDialItem_FieldNumber) {
  TSMetaDialItem_FieldNumber_DialId = 1,
  TSMetaDialItem_FieldNumber_IsBuiltin = 2,
  TSMetaDialItem_FieldNumber_IsSelect = 3,
};

/**
 * =============================================================
 * 表盘配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaDialItem : GPBMessage

/** 表盘ID */
@property(nonatomic, readwrite) uint64_t dialId;

/** 是否是内置表盘 */
@property(nonatomic, readwrite) BOOL isBuiltin;

/** 是否是当前选中的表盘 */
@property(nonatomic, readwrite) BOOL isSelect;

@end

#pragma mark - TSMetaDialList

typedef GPB_ENUM(TSMetaDialList_FieldNumber) {
  TSMetaDialList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaDialList : GPBMessage

/** 表盘列表，最大数量 100 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaDialItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaDialId

typedef GPB_ENUM(TSMetaDialId_FieldNumber) {
  TSMetaDialId_FieldNumber_DialId = 1,
};

GPB_FINAL @interface TSMetaDialId : GPBMessage

/** 表盘ID */
@property(nonatomic, readwrite) uint64_t dialId;

@end

#pragma mark - TSMetaWorldClockItem

typedef GPB_ENUM(TSMetaWorldClockItem_FieldNumber) {
  TSMetaWorldClockItem_FieldNumber_City = 1,
  TSMetaWorldClockItem_FieldNumber_ZoneId = 2,
  TSMetaWorldClockItem_FieldNumber_ZoneOffset = 3,
};

/**
 * =============================================================
 * 世界时钟配置
 * =============================================================
 **/
GPB_FINAL @interface TSMetaWorldClockItem : GPBMessage

/** 城市名称，最大长度 31 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

/** 时区ID，最大长度 31 字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *zoneId;

/** 时区偏移量，单位毫秒 */
@property(nonatomic, readwrite) int32_t zoneOffset;

@end

#pragma mark - TSMetaWorldClockList

typedef GPB_ENUM(TSMetaWorldClockList_FieldNumber) {
  TSMetaWorldClockList_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface TSMetaWorldClockList : GPBMessage

/** 世界时钟列表，最大数量 10 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaWorldClockItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TMetaPrayerConfig

typedef GPB_ENUM(TMetaPrayerConfig_FieldNumber) {
  TMetaPrayerConfig_FieldNumber_IsEnabled = 1,
  TMetaPrayerConfig_FieldNumber_ItemsArray = 2,
};

/**
 * =============================================================
 * 祈祷配置
 * =============================================================
 **/
GPB_FINAL @interface TMetaPrayerConfig : GPBMessage

/** 是否启用祈祷功能 */
@property(nonatomic, readwrite) BOOL isEnabled;

/** 每个类型的开关，最大数量 7 个 */
@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaPrayerTimes

typedef GPB_ENUM(TSMetaPrayerTimes_FieldNumber) {
  TSMetaPrayerTimes_FieldNumber_Timestamp = 1,
  TSMetaPrayerTimes_FieldNumber_ItemsArray = 2,
};

GPB_FINAL @interface TSMetaPrayerTimes : GPBMessage

/** 时间戳，距离2000年始的秒数 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 每个类型的时刻，最大数量 7 个 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - TSMetaPrayerDayList

typedef GPB_ENUM(TSMetaPrayerDayList_FieldNumber) {
  TSMetaPrayerDayList_FieldNumber_DaysArray = 1,
};

GPB_FINAL @interface TSMetaPrayerDayList : GPBMessage

/** 每天数据列表，最大数量 7 个 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TSMetaPrayerTimes*> *daysArray;
/** The number of items in @c daysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger daysArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
