#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "TopStepFitKit.h"
#import "TSFitAIManager.h"
#import "TSAlarmClockModel+Fit.h"
#import "TSFitAlarmClock.h"
#import "TSFitAppStore.h"
#import "TSBatteryModel+Fit.h"
#import "TSFitBattery.h"
#import "TSFitBleConnect.h"
#import "TSPeripheral+Fit.h"
#import "NSBundle+TSFit.h"
#import "TSFitCamera.h"
#import "TSFitComDataStorage.h"
#import "TSFitComKit.h"
#import "TopStepContactModel+Fit.h"
#import "TSFitContact.h"
#import "TSFitBaseDataSync.h"
#import "TSBOValueItem+Fit.h"
#import "TSFitBODataSync.h"
#import "TSBPValueItem+Fit.h"
#import "TSFitBPDataSync.h"
#import "TSDailyActivityItem+Fit.h"
#import "TSFitDailyActivityDataSync.h"
#import "TSFitEcgDataSync.h"
#import "TSFitHRDataSync.h"
#import "TSHRValueItem+Fit.h"
#import "TSSleepDailyModel+Fit.h"
#import "TSSleepDetailItem+Fit.h"
#import "TSFitSleepDataSync.h"
#import "TSSportItemModel+Fit.h"
#import "TSSportModel+Fit.h"
#import "TSSportSummaryModel+Fit.h"
#import "TSFitSportDataSync.h"
#import "TSFitStressDataSync.h"
#import "TSStressValueItem+Fit.h"
#import "TSFitTempDataSync.h"
#import "TSDataSyncConfig+Fit.h"
#import "TSFitDataSync.h"
#import "TSECardModel+Fit.h"
#import "TSFitECardBag.h"
#import "TSFemaleHealthConfig+Fit.h"
#import "TSFitFemaleHealth.h"
#import "TSFitGlasses.h"
#import "TSFirmwareKeyService.h"
#import "TSFitGoMoreSecret.h"
#import "TSNetworkManager.h"
#import "TSFitBloodOxygen.h"
#import "TSFitBloodPressure.h"
#import "TSDailyActivityGoals+Fit.h"
#import "TSFitDailyActivity.h"
#import "TSFitElectrocardio.h"
#import "TSActivityMeasureParam+Fit.h"
#import "TSFitActiveMeasure.h"
#import "TSAutoMonitorBPConfigs+Fit.h"
#import "TSAutoMonitorConfigs+Fit.h"
#import "TSAutoMonitorHRConfigs+Fit.h"
#import "TSFitAutoMonitor.h"
#import "TSFitBPAutoMonitor.h"
#import "TSFitHRAutoMonitor.h"
#import "TSFitHealthBase.h"
#import "TSFitHeartRate.h"
#import "TSFitSleep.h"
#import "TSFitSport.h"
#import "TSFitStress.h"
#import "TSFitTemperature.h"
#import "TSTempValueItem+Fit.h"
#import "TSFitKitBase.h"
#import "TSKitDevice.h"
#import "TSFitKitInit.h"
#import "TSFitLanguage.h"
#import "TSLanguageModel+Fit.h"
#import "TSFitMessage.h"
#import "TSMessageModel+Fit.h"
#import "TSFitMusic.h"
#import "TSFileTransferModel+Fit.h"
#import "TSFitFirmwareUpgrade.h"
#import "TSCustomDial+Fit.h"
#import "TSCustomDialTime+Fit.h"
#import "TSDialModel+Fit.h"
#import "TSFitPeripheralDial.h"
#import "TSFitPeripheralFind.h"
#import "TSFitPeripheralLog.h"
#import "TSFitPrayers.h"
#import "TSPrayerConfigs+Fit.h"
#import "TSPrayerTimes+Fit.h"
#import "TSFitReminders.h"
#import "TSRemindersModel+Fit.h"
#import "TSFitRemoteControl.h"
#import "TSFitRequestTransfer.h"
#import "TSDoNotDisturbModel+Fit.h"
#import "TSFitSetting.h"
#import "TSWristWakeUpModel+Fit.h"
#import "TSFitTime.h"
#import "TSFitUnit.h"
#import "TSFitUserInfo.h"
#import "TSUserInfoModel+Fit.h"
#import "TopStepWeather+Fit.h"
#import "TSFitWeather.h"
#import "TSWeatherCodeModel+Fit.h"
#import "TSWeatherDay+Fit.h"
#import "TSWeatherHour+Fit.h"
#import "TSFitWorldClock.h"
#import "TSWorldClockModel+Fit.h"

FOUNDATION_EXPORT double TopStepFitKitVersionNumber;
FOUNDATION_EXPORT const unsigned char TopStepFitKitVersionString[];

